/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-07-11 04:55:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/sh3/workspace-sts-3.9.18/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Shinhan_SW_1st_TeamProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/user/../common/header.jsp", Long.valueOf(1720433011362L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1719295440415L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    <!-- 헤더,푸터 css -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/header_footer.css\">\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>회원가입 페이지</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: Arial, sans-serif;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            background-color: #ffffff;\r\n");
      out.write("            color: #333;\r\n");
      out.write("        }\r\n");
      out.write("        header {\r\n");
      out.write("            background-color: #fff;\r\n");
      out.write("            padding: 10px 0;\r\n");
      out.write("        }\r\n");
      out.write("        header .logo {\r\n");
      out.write("            font-size: 2em;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("        .navbar {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            padding: 10px 0;\r\n");
      out.write("            border-bottom: 1px solid #eee;\r\n");
      out.write("        }\r\n");
      out.write("        .navbar a {\r\n");
      out.write("            margin: 0 15px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color: #333;\r\n");
      out.write("        }\r\n");
      out.write("        .container {\r\n");
      out.write("            max-width: 600px;\r\n");
      out.write("            height: 800px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            background-color: #fff;\r\n");
      out.write("            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            justify-content: space-between; /* 공간을 고르게 나눔 */\r\n");
      out.write("        }\r\n");
      out.write("        h1 {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        form {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            flex-grow: 1;\r\n");
      out.write("            justify-content: space-between; /* 공간을 고르게 나눔 */\r\n");
      out.write("        }\r\n");
      out.write("        .form-group {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: row;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("        }\r\n");
      out.write("        .form-group label {\r\n");
      out.write("            flex: 0 0 150px; /* 고정된 너비 설정 */\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("        .form-group input[type=\"text\"],\r\n");
      out.write("        .form-group input[type=\"password\"],\r\n");
      out.write("        .form-group input[type=\"email\"],\r\n");
      out.write("        .form-group input[type=\"date\"],\r\n");
      out.write("        .form-group select {\r\n");
      out.write("            flex: 1;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            border: 1px solid #ccc;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("        }\r\n");
      out.write("        .radio-group, .checkbox-group {\r\n");
      out.write("            /* margin-bottom: 15px; 삭제 */\r\n");
      out.write("        }\r\n");
      out.write("        .radio-group label,\r\n");
      out.write("        .checkbox-group label {\r\n");
      out.write("            margin-right: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        .radio-group input,\r\n");
      out.write("        .checkbox-group input {\r\n");
      out.write("            margin-right: 5px;\r\n");
      out.write("        }\r\n");
      out.write("        .btn {\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            background-color: #513AE4;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("        .btn:hover {\r\n");
      out.write("            background-color: #4331B7;\r\n");
      out.write("        }\r\n");
      out.write("        .error-message {\r\n");
      out.write("            font-size: 0.9em;\r\n");
      out.write("            margin-top: -10px;\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("        }\r\n");
      out.write("        .error-message.red {\r\n");
      out.write("            color: red;\r\n");
      out.write("        }\r\n");
      out.write("        .error-message.green {\r\n");
      out.write("            color: green;\r\n");
      out.write("        }\r\n");
      out.write("        .email-container {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: row;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("        .email-container input[type=\"email\"] {\r\n");
      out.write("            flex: 1;\r\n");
      out.write("            margin-right: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        .address-container {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("        }\r\n");
      out.write("        .hidden {\r\n");
      out.write("            display: none;\r\n");
      out.write("        }\r\n");
      out.write("        footer {\r\n");
      out.write("            background-color: #333;\r\n");
      out.write("            color: white;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            padding: 20px 0;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        footer .footer-line {\r\n");
      out.write("            border-top: 1px solid #555;\r\n");
      out.write("            margin: 10px 0;\r\n");
      out.write("        }\r\n");
      out.write("        footer .footer-text {\r\n");
      out.write("            margin: 5px 0;\r\n");
      out.write("        }\r\n");
      out.write("        footer .footer-logo {\r\n");
      out.write("            font-size: 2em;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        footer .footer-links {\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        footer .footer-links a {\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            margin: 0 10px;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("        var verificationCode = '';\r\n");
      out.write("\r\n");
      out.write("        // 초기 상태: 브랜드 input 숨기기\r\n");
      out.write("        $('#brand-group').addClass('hidden');\r\n");
      out.write("\r\n");
      out.write("        // 구분 선택에 따라 아이디 레이블 변경 및 브랜드 input 표시/숨기기\r\n");
      out.write("        $('#member_type').on('change', function() {\r\n");
      out.write("            var selectedType = $(this).val();\r\n");
      out.write("            if (selectedType == '2') {\r\n");
      out.write("                $('label[for=\"member_id\"]').text('사업자등록번호');\r\n");
      out.write("                $('#brand-group').removeClass('hidden');\r\n");
      out.write("            } else {\r\n");
      out.write("                $('label[for=\"member_id\"]').text('아이디');\r\n");
      out.write("                $('#brand-group').addClass('hidden');\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // 이메일 인증번호 받기\r\n");
      out.write("        $('#email-verify-btn').on('click', function() {\r\n");
      out.write("            var email = $('#email').val();\r\n");
      out.write("            if (email) {\r\n");
      out.write("                $.ajax({\r\n");
      out.write("                    url: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member_test/sendEmailVerification',\r\n");
      out.write("                    type: 'POST',\r\n");
      out.write("                    data: { email: email },\r\n");
      out.write("                    success: function(response) {\r\n");
      out.write("                        if (response.success) {\r\n");
      out.write("                            verificationCode = response.verificationCode;\r\n");
      out.write("                            alert('인증번호가 이메일로 전송되었습니다.');\r\n");
      out.write("                            $('#email-verification-popup').show();\r\n");
      out.write("                        } else {\r\n");
      out.write("                            alert('이메일 전송에 실패했습니다.');\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("            } else {\r\n");
      out.write("                alert('이메일을 입력해주세요.');\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // 이메일 인증번호 확인\r\n");
      out.write("        $('#verify-code-btn').on('click', function() {\r\n");
      out.write("            var enteredCode = $('#verification-code').val();\r\n");
      out.write("            if (enteredCode === verificationCode) {\r\n");
      out.write("                alert('이메일 인증이 완료되었습니다.');\r\n");
      out.write("                $('#email').prop('readonly', true);\r\n");
      out.write("                $('#email-verification-popup').hide();\r\n");
      out.write("            } else {\r\n");
      out.write("                alert('인증번호가 올바르지 않습니다.');\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // 비밀번호 확인 기능\r\n");
      out.write("        $('#confirm-password').on('input', function() {\r\n");
      out.write("            var password = $('#member_pw').val();\r\n");
      out.write("            var confirmPassword = $(this).val();\r\n");
      out.write("            if (password === '' || confirmPassword === '') {\r\n");
      out.write("                $('#password-error').text('').removeClass('red green');\r\n");
      out.write("            } else if (password !== confirmPassword) {\r\n");
      out.write("                $('#password-error').text('비밀번호가 다릅니다.').removeClass('green').addClass('red');\r\n");
      out.write("            } else {\r\n");
      out.write("                $('#password-error').text('비밀번호가 일치합니다.').removeClass('red').addClass('green');\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // 주소 입력 버튼 클릭 시 카카오 API 호출\r\n");
      out.write("        $('#address-btn').on('click', function() {\r\n");
      out.write("            new daum.Postcode({\r\n");
      out.write("                oncomplete: function(data) {\r\n");
      out.write("                    var addr = ''; // 주소 변수\r\n");
      out.write("                    var extraAddr = ''; // 참고항목 변수\r\n");
      out.write("\r\n");
      out.write("                    // 사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.\r\n");
      out.write("                    if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우\r\n");
      out.write("                        addr = data.roadAddress;\r\n");
      out.write("                    } else { // 사용자가 지번 주소를 선택했을 경우(J)\r\n");
      out.write("                        addr = data.jibunAddress;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    // 사용자가 선택한 주소가 도로명 타입일때 참고항목을 조합한다.\r\n");
      out.write("                    if (data.userSelectedType === 'R') {\r\n");
      out.write("                        if (data.bname !== '' && /[동|로|가]$/g.test(data.bname)) {\r\n");
      out.write("                            extraAddr += data.bname;\r\n");
      out.write("                        }\r\n");
      out.write("                        if (data.buildingName !== '' && data.apartment === 'Y') {\r\n");
      out.write("                            extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);\r\n");
      out.write("                        }\r\n");
      out.write("                        if (extraAddr !== '') {\r\n");
      out.write("                            extraAddr = ' (' + extraAddr + ')';\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    // 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("                    document.getElementById('zipcode').value = data.zonecode;\r\n");
      out.write("                    document.getElementById(\"main_address\").value = addr;\r\n");
      out.write("                    document.getElementById(\"sub_address\").value = extraAddr;\r\n");
      out.write("                    document.getElementById(\"detail_address\").focus();\r\n");
      out.write("                }\r\n");
      out.write("            }).open();\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // 회원가입 폼 제출\r\n");
      out.write("        $('form').on('submit', function(event) {\r\n");
      out.write("            var password = $('#member_pw').val();\r\n");
      out.write("            var confirmPassword = $('#confirm-password').val();\r\n");
      out.write("            var emailVerified = $('#email').prop('readonly');\r\n");
      out.write("            var allFieldsFilled = true;\r\n");
      out.write("            var errorMessage = '모든 칸을 기입해주세요.';\r\n");
      out.write("\r\n");
      out.write("            // 필수 입력 칸 체크\r\n");
      out.write("            $('input[required]').each(function() {\r\n");
      out.write("                if ($(this).val() === '') {\r\n");
      out.write("                    allFieldsFilled = false;\r\n");
      out.write("                    return false; // 필수 입력 칸이 비어 있으면 루프 종료\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            if (!emailVerified) {\r\n");
      out.write("                event.preventDefault();\r\n");
      out.write("                $('#email-error').text('이메일을 인증해 주세요.');\r\n");
      out.write("            } else if (password === '' || confirmPassword === '' || password !== confirmPassword) {\r\n");
      out.write("                event.preventDefault();\r\n");
      out.write("                $('#password-error').text('비밀번호를 설정해주세요.').removeClass('green').addClass('red');\r\n");
      out.write("            } else if (!allFieldsFilled) {\r\n");
      out.write("                event.preventDefault();\r\n");
      out.write("                $('#form-error').text(errorMessage).addClass('red');\r\n");
      out.write("            } else {\r\n");
      out.write("                alert('회원가입 완료!');\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("	<div class=\"header_top inner\">\r\n");
      out.write("		<div class=\"leftGnb\">\r\n");
      out.write("			<h1 class=\"logo\">\r\n");
      out.write("				<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">\r\n");
      out.write("					<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/logo_main.png\" alt=\"메인로고\">\r\n");
      out.write("				</a>\r\n");
      out.write("			</h1>\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("			<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\" class=\"search_form\">\r\n");
      out.write("				<label for=\"search_wrap\"> \r\n");
      out.write("					<input name=\"search_input\" type=\"search\" /> \r\n");
      out.write("					<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/icon_serch.png\" alt=\"돋보기 아이콘\" class=\"search_img\" />\r\n");
      out.write("				</label>\r\n");
      out.write("			</form>\r\n");
      out.write("		</div> \r\n");
      out.write("		<div class=\"rightGnb\">  \r\n");
      out.write("			<ul>\r\n");
      out.write("				");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				<li>\r\n");
      out.write("					<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/customer/myPage.do\">\r\n");
      out.write("						<p>마이페이지</p>\r\n");
      out.write("						<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/icon-person2.png\" alt=\"마이페이지\" class=\"myPageIcon\">\r\n");
      out.write("					</a>\r\n");
      out.write("					");
      out.write("\r\n");
      out.write("					");
      out.write("\r\n");
      out.write("				</li>\r\n");
      out.write("				<li>\r\n");
      out.write("					<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cart/cart.do\">\r\n");
      out.write("						<p>장바구니</p>\r\n");
      out.write("						<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/icon-cart.png\" alt=\"장바구니\">\r\n");
      out.write("					</a>\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("	\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"header_bottom\">\r\n");
      out.write("		<div class=\"menu_wrap inner\">\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("			<ul class=\"left_menu\">\r\n");
      out.write("				<li data-menu=\"0\">\r\n");
      out.write("					<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/prod/productlist?shwCtgNum=11000000\"\r\n");
      out.write("					class=\"category_name\">여성</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li data-menu=\"1\">\r\n");
      out.write("					<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/prod/productlist?shwCtgNum=14000000\"\r\n");
      out.write("					class=\"category_name\">남성</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li data-menu=\"2\">\r\n");
      out.write("					<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/prod/productlist?shwCtgNum=13000000\"\r\n");
      out.write("					class=\"category_name\">키즈</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li data-menu=\"3\">\r\n");
      out.write("					<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/prod/productlist?shwCtgNum=15000000\"\r\n");
      out.write("					class=\"category_name\">럭셔리</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li data-menu=\"4\">\r\n");
      out.write("					<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/prod/productlist?shwCtgNum=12000000\"\r\n");
      out.write("					class=\"category_name\">스포츠</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li data-menu=\"5\">\r\n");
      out.write("					<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/prod/productlist?shwCtgNum=10000000\"\r\n");
      out.write("					class=\"category_name\">가방＆신발</a>\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("			<ul class=\"right_menu\">\r\n");
      out.write("				<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/customer/coordination.do\" class=\"highlight\">AI추천코디</a></li>\r\n");
      out.write("				<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/customer/productlist\" class=\"highlight\">옷대여</a></li>\r\n");
      out.write("				<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/adminqna/myqna.do\">Q&A</a></li>\r\n");
      out.write("				<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/notice/notices\">공지사항</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("		<div class=\"menu-backgorund\"></div>\r\n");
      out.write("		<div class=\"menu_pan inner\">\r\n");
      out.write("			<div class=\"dropdown_nav\">\r\n");
      out.write("\r\n");
      out.write("				<ul ctg=\"women\">\r\n");
      out.write("				</ul>\r\n");
      out.write("				<ul ctg=\"men\">\r\n");
      out.write("				</ul>\r\n");
      out.write("				<ul ctg=\"kids\">\r\n");
      out.write("				</ul>\r\n");
      out.write("				<ul ctg=\"luxury\">\r\n");
      out.write("				</ul>\r\n");
      out.write("				<ul ctg=\"sports\">\r\n");
      out.write("				</ul>\r\n");
      out.write("				<ul ctg=\"bagAndShoes\">\r\n");
      out.write("				</ul>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</header>\r\n");
      out.write("<script>\r\n");
      out.write("	$(function() {\r\n");
      out.write("		//$.noConflict(); //제이쿼리 충돌방지\r\n");
      out.write("		//메뉴 드롭 다운\r\n");
      out.write("		var isFirstHover = true; // 처음 마우스를 올리는지 여부를 추적\r\n");
      out.write("\r\n");
      out.write("		$(\".left_menu > li\").on(\"mouseenter\", function() {\r\n");
      out.write("			var menuIndex = $(this).data(\"menu\"); // data-menu 속성 값을 가져옴\r\n");
      out.write("			\r\n");
      out.write("	        $(\".left_menu > li\").css({\r\n");
      out.write("	            \"color\": \"#ccc\",\r\n");
      out.write("	            \"font-weight\": \"normal\"\r\n");
      out.write("	        }); // 모든 li를 #ccc 색상으로 변경하고 폰트 두께를 정상으로 설정\r\n");
      out.write("	        $(this).css({\r\n");
      out.write("	            \"color\": \"black\",\r\n");
      out.write("	            \"font-weight\": \"bold\"\r\n");
      out.write("	        }); // 호버한 li만 검정색으로 변경하고 폰트 두께를 두껍게 설정\r\n");
      out.write("			\r\n");
      out.write("			if (isFirstHover) {\r\n");
      out.write("				$(\".dropdown_nav ul\").stop().animate({\r\n");
      out.write("					height : \"0\"\r\n");
      out.write("				}, 500); // 모든 서브메뉴 높이 0으로 설정\r\n");
      out.write("				$(\".dropdown_nav ul\").eq(menuIndex).stop().animate({\r\n");
      out.write("					height : \"400px\"\r\n");
      out.write("				}, 500);\r\n");
      out.write("				$(\".dropdown_nav\").stop().animate({\r\n");
      out.write("					height : \"400px\"\r\n");
      out.write("				}, 500); // 서브메뉴 표시\r\n");
      out.write("	            $(\".menu-backgorund\").css(\"display\",\"block\");\r\n");
      out.write("				\r\n");
      out.write("				isFirstHover = false; // 이후 마우스 이동 시 애니메이션 제거\r\n");
      out.write("			} else {\r\n");
      out.write("				$(\".dropdown_nav ul\").css(\"height\", \"0\"); // 모든 서브메뉴 높이 0으로 설정\r\n");
      out.write("				$(\".dropdown_nav ul\").eq(menuIndex).css(\"height\", \"400px\");\r\n");
      out.write("				$(\".dropdown_nav\").css(\"height\", \"400px\"); // 서브메뉴 표시\r\n");
      out.write("	            $(\".menu-backgorund\").css(\"display\", \"blcok\"); // 배경 표시\r\n");
      out.write("	            \r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		$(\".dropdown_nav\").on(\"mouseleave\", function() {\r\n");
      out.write("		   $(\".left_menu > li\").css({\r\n");
      out.write("	            \"color\": \"black\",\r\n");
      out.write("	            \"font-weight\": \"normal\"\r\n");
      out.write("	        }); // 모든 li 색상을 기본으로 변경하고 폰트 두께를 정상으로 설정\r\n");
      out.write("			// 마우스가 떠났을 때 서브메뉴 높이 초기화\r\n");
      out.write("			$(\".dropdown_nav ul\").css(\"height\", \"0\");\r\n");
      out.write("			$(\".dropdown_nav\").css(\"height\", \"0\");\r\n");
      out.write("	        $(\".menu-backgorund\").css(\"display\",\"none\"); // 배경 숨김	\r\n");
      out.write("			isFirstHover = true; // 마우스를 떠났을 때 다시 애니메이션 활성화\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("		});\r\n");
      out.write("	\r\n");
      out.write("		var h_ctg = {\r\n");
      out.write("				'women':11000000,\r\n");
      out.write("				'men':14000000,\r\n");
      out.write("				'kids':13000000,\r\n");
      out.write("				'luxury':15000000,\r\n");
      out.write("				'sports':12000000,\r\n");
      out.write("				'bagAndShoes':10000000\r\n");
      out.write("		}\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/prod/headerctg\",\r\n");
      out.write("			type:'post',\r\n");
      out.write("			data:JSON.stringify(h_ctg),\r\n");
      out.write("			dataType: \"json\",\r\n");
      out.write("			contentType:\"application/json\",\r\n");
      out.write("			success: function(ctgMap) {\r\n");
      out.write("				for(var key in ctgMap) {\r\n");
      out.write("					$('.dropdown_nav').find(`ul[ctg='${key}']`).append(`<li><a href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/prod/productlist?shwCtgNum=${ctgMap[key][0].parent_category_id}'>전체 상품</a></li>`);\r\n");
      out.write("					$(ctgMap[key]).each(function(index, ctgVO) {\r\n");
      out.write("						$('.dropdown_nav').find(`ul[ctg='${key}']`).append(`<li><a href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/prod/productlist?shwCtgNum=${ctgVO.category_id}'>${ctgVO.category_name}</a></li>`);\r\n");
      out.write("					});\r\n");
      out.write("				}\r\n");
      out.write("			},\r\n");
      out.write("			error: function() {\r\n");
      out.write("				\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <h1>회원가입</h1>\r\n");
      out.write("        <div id=\"form-error\" class=\"error-message red\"></div>\r\n");
      out.write("        <form method=\"post\" accept-charset=\"UTF-8\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member_test/signup\">\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"member_type\">구분</label>\r\n");
      out.write("                <select id=\"member_type\" name=\"member_type\">\r\n");
      out.write("                    <option value=\"1\">고객</option>\r\n");
      out.write("                    <option value=\"2\">판매자</option>\r\n");
      out.write("                </select>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"member_id\">아이디</label>\r\n");
      out.write("                <input type=\"text\" id=\"member_id\" name=\"member_id\" placeholder=\"영문, 숫자, 특수문자('_')만 입력 가능\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"member_pw\">비밀번호</label>\r\n");
      out.write("                <input type=\"password\" id=\"member_pw\" name=\"member_pw\" placeholder=\"영문, 숫자, 특수문자 조합 9자리 이상\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"confirm-password\">비밀번호 확인</label>\r\n");
      out.write("                <input type=\"password\" id=\"confirm-password\" name=\"confirmPassword\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"password-error\" class=\"error-message\"></div>\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"member_name\">이름</label>\r\n");
      out.write("                <input type=\"text\" id=\"member_name\" name=\"member_name\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"phone\">휴대폰 번호</label>\r\n");
      out.write("                <input type=\"text\" id=\"phone\" name=\"phone\" placeholder=\"01012345678, ('-'를 빼고 입력해주세요)\" pattern=\"[0-9]{11}\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"email\">이메일</label>\r\n");
      out.write("                <div class=\"email-container\">\r\n");
      out.write("                    <input type=\"email\" id=\"email\" name=\"email\" required>\r\n");
      out.write("                    <button type=\"button\" id=\"email-verify-btn\" class=\"btn\">인증번호 받기</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"email-error\" class=\"error-message red\"></div>\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"birth_date\">생년월일</label>\r\n");
      out.write("                <input type=\"date\" id=\"birth_date\" name=\"birth_date\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group radio-group\">\r\n");
      out.write("                <label>성별</label>\r\n");
      out.write("                <input type=\"radio\" id=\"male\" name=\"gender\" value=\"M\" required>\r\n");
      out.write("                <label for=\"male\">남성</label>\r\n");
      out.write("                <input type=\"radio\" id=\"female\" name=\"gender\" value=\"F\" required>\r\n");
      out.write("                <label for=\"female\">여성</label>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"zipcode\">주소</label>\r\n");
      out.write("                <button type=\"button\" id=\"address-btn\" class=\"btn address-button\">주소 입력</button>\r\n");
      out.write("                <input type=\"text\" id=\"zipcode\" name=\"zipcode\" placeholder=\"우편번호\" readonly required>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"main_address\"></label>\r\n");
      out.write("                <input type=\"text\" id=\"main_address\" name=\"main_address\" placeholder=\"주소\" readonly required>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"detail_address\"></label>\r\n");
      out.write("                <input type=\"text\" id=\"detail_address\" name=\"detail_address\" placeholder=\"상세주소\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"sub_address\"></label>\r\n");
      out.write("                <input type=\"text\" id=\"sub_address\" name=\"sub_address\" placeholder=\"참고주소\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group hidden\" id=\"brand-group\">\r\n");
      out.write("                <label for=\"brand\">브랜드</label>\r\n");
      out.write("                <input type=\"text\" id=\"brand\" name=\"brand\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <button type=\"submit\" class=\"btn\">가입하기</button>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- 이메일 인증 팝업 -->\r\n");
      out.write("    <div id=\"email-verification-popup\" style=\"display:none;\">\r\n");
      out.write("        <div style=\"background:rgba(0,0,0,0.5);position:fixed;top:0;left:0;width:100%;height:100%;z-index:10;\"></div>\r\n");
      out.write("        <div style=\"background:#fff;position:fixed;top:50%;left:50%;transform:translate(-50%,-50%);padding:20px;z-index:20;\">\r\n");
      out.write("            <h2>이메일 인증</h2>\r\n");
      out.write("            <input type=\"text\" id=\"verification-code\" placeholder=\"인증번호를 입력하세요\">\r\n");
      out.write("            <button id=\"verify-code-btn\" class=\"btn\">확인</button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <footer>\r\n");
      out.write("        <div class=\"footer-text\">회사소개 이용약관 개인정보처리방침 이메일무단수집거부 단체주문 제휴문의 입점신청 멤버쉽 안내</div>\r\n");
      out.write("        <div class=\"footer-logo\">saren</div>\r\n");
      out.write("        <div class=\"footer-links\">\r\n");
      out.write("            <a href=\"#\">고객센터</a>\r\n");
      out.write("            <a href=\"#\">공지사항</a>\r\n");
      out.write("            <a href=\"#\">매장찾기</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"footer-text\">\r\n");
      out.write("            서울특별시 강남구 남부순환로 2806 (도곡동) 대표 : 김태한 사업자등록번호: 101-85-43800 사업자정보확인 통신판매업신고: 2015-서울강남-02894\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"footer-text\">\r\n");
      out.write("            호스팅서비스: 삼성물산(주)패션부문 KG이니시스 구매안전서비스 이용확인 서비스가입사실확인\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"footer-text\">\r\n");
      out.write("            대표전화 1599-0007(유료) 080-700-1472(무료)\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"footer-text\">\r\n");
      out.write("            Copyright ⓒ 2003 Samsung C&T Corporation. All rights reserved\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/user/signup.jsp(7,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path");
      // /WEB-INF/views/user/signup.jsp(7,4) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/user/signup.jsp(7,4) '${pageContext.servletContext.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.servletContext.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /WEB-INF/views/user/signup.jsp(295,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("path");
      // /WEB-INF/views/user/signup.jsp(295,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/user/signup.jsp(295,0) '${pageContext.servletContext.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.servletContext.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f2_reused = false;
    try {
      _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f2.setParent(null);
      // /WEB-INF/views/user/../common/header.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setVar("path");
      // /WEB-INF/views/user/../common/header.jsp(4,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/user/../common/header.jsp(4,0) '${pageContext.servletContext.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.servletContext.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
      if (_jspx_th_c_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
      _jspx_th_c_005fset_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f3 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f3_reused = false;
    try {
      _jspx_th_c_005fset_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f3.setParent(null);
      // /WEB-INF/views/user/../common/header.jsp(7,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f3.setVar("isLoggedIn");
      // /WEB-INF/views/user/../common/header.jsp(7,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f3.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/user/../common/header.jsp(7,0) '${not empty sessionScope.member}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${not empty sessionScope.member}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f3 = _jspx_th_c_005fset_005f3.doStartTag();
      if (_jspx_th_c_005fset_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f3);
      _jspx_th_c_005fset_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("					");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("					");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/user/../common/header.jsp(30,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${isLoggedIn}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("						<li>\r\n");
          out.write("							<a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member_test/logout.do\"> \r\n");
          out.write("								<p>로그아웃</p>\r\n");
          out.write("								<img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/images/icon-logout.png\" alt=\"로그아웃\">\r\n");
          out.write("							</a>\r\n");
          out.write("						</li>\r\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("						<li>\r\n");
          out.write("							<a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member_test/login.do\" id=\"loginLink\"> \r\n");
          out.write("								<p>로그인</p>\r\n");
          out.write("								<img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/images/icon-login.gif\" alt=\"로그인\">\r\n");
          out.write("							</a>\r\n");
          out.write("						</li>\r\n");
          out.write("						<li>\r\n");
          out.write("							<a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member_test/signup\">\r\n");
          out.write("								<p>회원가입</p>\r\n");
          out.write("								<img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/images/icon-sign-in.png\" alt=\"회원가입\">\r\n");
          out.write("							</a>\r\n");
          out.write("						</li>\r\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
