/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-07-08 12:39:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.seller;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class seller_005fSellStock_005fmodifyPrd_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/sh3/workspace-sts-3.9.18/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Shinhan_SW_1st_TeamProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/seller/../common/header.jsp", Long.valueOf(1720433011362L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1719295440415L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>판매자_상품수정</title>\r\n");
      out.write("<!-- 본문 css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/style.css\">\r\n");
      out.write("<!-- 헤더,푸터 css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/header_footer.css\">\r\n");
      out.write("<!-- jquery 연결 -->\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>\r\n");
      out.write("<!-- 페이지용 css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/prdAdd.css\" />\r\n");
      out.write("<style>\r\n");
      out.write(".hidden {\r\n");
      out.write("	display: none;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("	let fileCount = document\r\n");
      out.write("			.querySelectorAll('#prdImgFileContainer .file-item').length;\r\n");
      out.write("	const maxFileCount = 5;\r\n");
      out.write("\r\n");
      out.write("	let mainImgFileCount = 0;//메인 사진 개수\r\n");
      out.write("	let descImgFileCount = 0;//설명 사진 개수\r\n");
      out.write("\r\n");
      out.write("	//1.메인 사진 업로드 추가\r\n");
      out.write("	function addMainImgFile() {\r\n");
      out.write("		if (mainImgFileCount >= 5) {\r\n");
      out.write("			alert(\"메인 사진은 최대 5개까지 추가할 수 있습니다.\");\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		// 새로운 파일 항목 생성\r\n");
      out.write("		const fileItem = document.createElement('div');\r\n");
      out.write("		fileItem.className = 'file-item';\r\n");
      out.write("\r\n");
      out.write("		// 파일 선택 필드 생성\r\n");
      out.write("		const fileField = document.createElement('input');\r\n");
      out.write("		fileField.className = 'file-input';\r\n");
      out.write("		fileField.type = 'file';\r\n");
      out.write("		fileField.name = 'mainImgFile';\r\n");
      out.write("		fileField.accept = '.jpg,.jpeg,.png';\r\n");
      out.write("		fileField.onchange = function(event) {\r\n");
      out.write("			setProdDescribeImg(event, fileItem);\r\n");
      out.write("		};\r\n");
      out.write("\r\n");
      out.write("		//파일 항목 삭제 버튼 생성\r\n");
      out.write("		const fileRemove = document.createElement('button');\r\n");
      out.write("		fileRemove.classname = 'file-remove';\r\n");
      out.write("		fileRemove.type = 'button';\r\n");
      out.write("		fileRemove.innerText = '삭제';\r\n");
      out.write("		fileRemove.onclick = function() {\r\n");
      out.write("			removeFile(this);\r\n");
      out.write("		};\r\n");
      out.write("\r\n");
      out.write("		fileItem.appendChild(fileField);\r\n");
      out.write("		fileItem.appendChild(fileRemove);\r\n");
      out.write("\r\n");
      out.write("		document.getElementById('prdMainImgFileContainer')\r\n");
      out.write("				.appendChild(fileItem);\r\n");
      out.write("\r\n");
      out.write("		mainImgFileCount = getMainFileItemCount();\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function getMainFileItemCount() {\r\n");
      out.write("		return document.querySelectorAll('#prdMainImgFileContainer .file-item').length;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	//2.설명사진 업로드 추가\r\n");
      out.write("	function addDescImgFile() {\r\n");
      out.write("		if (descImgFileCount >= 8) {\r\n");
      out.write("			alert(\"상품 설명 사진은 최대 8개까지 추가할 수 있습니다.\");\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		// 새로운 파일 항목 생성\r\n");
      out.write("		const fileItem = document.createElement('div');\r\n");
      out.write("		fileItem.className = 'file-item';\r\n");
      out.write("\r\n");
      out.write("		// 파일 선택 필드 생성\r\n");
      out.write("		const fileField = document.createElement('input');\r\n");
      out.write("		fileField.className = 'file-input';\r\n");
      out.write("		fileField.type = 'file';\r\n");
      out.write("		fileField.name = 'descImgFile';\r\n");
      out.write("		fileField.accept = '.jpg,.jpeg,.png';\r\n");
      out.write("		fileField.onchange = function(event) {\r\n");
      out.write("			setProdDescribeImg(event, fileItem);\r\n");
      out.write("		};\r\n");
      out.write("\r\n");
      out.write("		//파일 항목 삭제 버튼 생성\r\n");
      out.write("		const fileRemove = document.createElement('button');\r\n");
      out.write("		fileRemove.classname = 'file-remove';\r\n");
      out.write("		fileRemove.type = 'button';\r\n");
      out.write("		fileRemove.innerText = '삭제';\r\n");
      out.write("		fileRemove.onclick = function() {\r\n");
      out.write("			removeFile(this);\r\n");
      out.write("		};\r\n");
      out.write("\r\n");
      out.write("		fileItem.appendChild(fileField);\r\n");
      out.write("		fileItem.appendChild(fileRemove);\r\n");
      out.write("\r\n");
      out.write("		document.getElementById('prdDescImgFileContainer')\r\n");
      out.write("				.appendChild(fileItem);\r\n");
      out.write("\r\n");
      out.write("		descImgFileCount = getDescFileItemCount();\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function getDescFileItemCount() {\r\n");
      out.write("		return document.querySelectorAll('#prdDescImgFileContainer .file-item').length;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function removeFile(button) {\r\n");
      out.write("		// 부모 요소(file-item) 제거\r\n");
      out.write("		button.parentNode.remove();\r\n");
      out.write("		fileCount = getFileItemCount();\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function setProdDescribeImg(event, fileItem) {\r\n");
      out.write("		var file = event.target.files[0];\r\n");
      out.write("		var reader = new FileReader();\r\n");
      out.write("		reader.onload = function(event) {\r\n");
      out.write("			var imgContainer = document.createElement(\"div\");\r\n");
      out.write("			imgContainer.classList.add(\"prdImgFile\");\r\n");
      out.write("			var img = document.createElement(\"img\");\r\n");
      out.write("			img.setAttribute(\"src\", event.target.result);\r\n");
      out.write("			imgContainer.appendChild(img);\r\n");
      out.write("\r\n");
      out.write("			fileItem.appendChild(imgContainer);\r\n");
      out.write("		};\r\n");
      out.write("		reader.readAsDataURL(file);\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	//메인사진 미리보기 삭제 및 데이터 초기화\r\n");
      out.write("	function resetMainProdImg() {\r\n");
      out.write("		var prodid = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ProductInfo.prod_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("		alert(prodid);\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type : \"POST\",\r\n");
      out.write("			url : \"/shoppingmall/seller/resetMainProdImg\",\r\n");
      out.write("			contentType: 'application/json',\r\n");
      out.write("			data: JSON.stringify({prodid:prodid}),\r\n");
      out.write("			success : function(response) {\r\n");
      out.write("				// 서버에서 반환한 문자열에 따라 처리\r\n");
      out.write("				if (response === \"resetImgSuccess\") {\r\n");
      out.write("					console.log(\"상품 메인 이미지 목록 초기화 성공\");\r\n");
      out.write("					// 성공했을 때 추가적인 작업 수행\r\n");
      out.write("					// 예: 다른 UI 업데이트, 메시지 표시 등\r\n");
      out.write("					document.getElementById('mainImgSection').classList.remove('hidden');\r\n");
      out.write("					$(\"#prdMainImgPreview\").empty();\r\n");
      out.write("				} else if (response === \"resetImgFail\") {\r\n");
      out.write("					console.log(\"이미지 초기화 실패\");\r\n");
      out.write("					// 실패했을 때의 처리\r\n");
      out.write("					// 예: 경고 메시지 표시 등\r\n");
      out.write("				} else {\r\n");
      out.write("					console.log(\"알 수 없는 응답: \" + response);\r\n");
      out.write("					// 다른 응답에 대한 처리\r\n");
      out.write("				}\r\n");
      out.write("			},\r\n");
      out.write("			error : function(xhr, status, error) {\r\n");
      out.write("				console.error(error);\r\n");
      out.write("				// 실패 시 처리\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	//설명사진 미리보기 삭제 및 데이터 초기화\r\n");
      out.write("	function resetDescProdImg() {\r\n");
      out.write("		var prodid = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ProductInfo.prod_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("		alert(prodid);\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type : \"POST\",\r\n");
      out.write("			url : \"/shoppingmall/seller/resetDescProdImg\",\r\n");
      out.write("			contentType: 'application/json',\r\n");
      out.write("			data: JSON.stringify({prodid:prodid}),\r\n");
      out.write("			success : function(response) {\r\n");
      out.write("				// 서버에서 반환한 문자열에 따라 처리\r\n");
      out.write("				if (response === \"resetImgSuccess\") {\r\n");
      out.write("					console.log(\"상품 메인 이미지 초기화 성공\");\r\n");
      out.write("					// 성공했을 때 추가적인 작업 수행\r\n");
      out.write("					// 예: 다른 UI 업데이트, 메시지 표시 등\r\n");
      out.write("					document.getElementById('descImgSection').classList.remove('hidden');\r\n");
      out.write("					$(\"#prdDescImgPreview\").empty();\r\n");
      out.write("				} else if (response === \"resetImgFail\") {\r\n");
      out.write("					console.log(\"이미지 초기화 실패\");\r\n");
      out.write("					// 실패했을 때의 처리\r\n");
      out.write("					// 예: 경고 메시지 표시 등\r\n");
      out.write("				} else {\r\n");
      out.write("					console.log(\"알 수 없는 응답: \" + response);\r\n");
      out.write("					// 다른 응답에 대한 처리\r\n");
      out.write("				}\r\n");
      out.write("			},\r\n");
      out.write("			error : function(xhr, status, error) {\r\n");
      out.write("				console.error(error);\r\n");
      out.write("				// 실패 시 처리\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	//Depth = 1인 항목들에서 선택\r\n");
      out.write("	function firstDepth() {\r\n");
      out.write("		var selectedValue = document.getElementById(\"depth1\").value;\r\n");
      out.write("\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type : 'POST',\r\n");
      out.write("			url : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/seller/find2ndCategoryList.do',\r\n");
      out.write("			contentType : 'application/json',\r\n");
      out.write("			data : JSON.stringify(selectedValue),\r\n");
      out.write("			success : function(response) {\r\n");
      out.write("				console.log(response);\r\n");
      out.write("				//location.reload();\r\n");
      out.write("\r\n");
      out.write("				// depth2 요소가 이미 존재하는 경우 제거\r\n");
      out.write("				var existingSelect = document.getElementById('depth2');\r\n");
      out.write("				if (existingSelect) {\r\n");
      out.write("					existingSelect.remove();\r\n");
      out.write("				}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				// 새로운 <select> 요소 depth2 생성\r\n");
      out.write("				var newSelect = document.createElement('select');\r\n");
      out.write("				newSelect.className = 'prdCategory';\r\n");
      out.write("				newSelect.id = 'depth2'; // ID가 중복되지 않도록 확인 필요\r\n");
      out.write("				newSelect.setAttribute('onchange', 'secondDepth()');\r\n");
      out.write("\r\n");
      out.write("				\r\n");
      out.write("				// Add default option\r\n");
      out.write("                var defaultOption = document.createElement('option');\r\n");
      out.write("                defaultOption.value = 0;\r\n");
      out.write("                defaultOption.textContent = '카테고리 선택';\r\n");
      out.write("                newSelect.appendChild(defaultOption);\r\n");
      out.write("\r\n");
      out.write("				// Add options based on response\r\n");
      out.write("				response.forEach(function(category) {\r\n");
      out.write("					var option = document.createElement('option');\r\n");
      out.write("					option.value = category.category_id;\r\n");
      out.write("					option.textContent = category.category_name;\r\n");
      out.write("					newSelect.appendChild(option);\r\n");
      out.write("				});\r\n");
      out.write("\r\n");
      out.write("				// categoryContainer에 새로운 <select> 추가\r\n");
      out.write("				var categoryContainer = document\r\n");
      out.write("						.querySelector('.categoryContainer');\r\n");
      out.write("				categoryContainer.appendChild(newSelect);\r\n");
      out.write("			},\r\n");
      out.write("			error : function(xhr, status, error) {\r\n");
      out.write("				console.error('AJAX 오류:', status, error);\r\n");
      out.write("			}\r\n");
      out.write("		})\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function secondDepth() {\r\n");
      out.write("		var selectedValue = document.getElementById(\"depth2\").value;\r\n");
      out.write("\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type : 'POST',\r\n");
      out.write("			url : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/seller/find3rdCategoryList.do',\r\n");
      out.write("			contentType : 'application/json',\r\n");
      out.write("			data : JSON.stringify(selectedValue),\r\n");
      out.write("			success : function(response) {\r\n");
      out.write("				console.log(response);\r\n");
      out.write("				//location.reload();\r\n");
      out.write("				\r\n");
      out.write("				// depth3 요소가 이미 존재하는 경우 제거\r\n");
      out.write("				var existingSelect = document.getElementById('depth3');\r\n");
      out.write("				if (existingSelect) {\r\n");
      out.write("					existingSelect.remove();\r\n");
      out.write("				}\r\n");
      out.write("\r\n");
      out.write("				// 새로운 <select> 요소 depth3 생성\r\n");
      out.write("				var newSelect = document.createElement('select');\r\n");
      out.write("				newSelect.className = 'prdCategory';\r\n");
      out.write("				newSelect.id = 'depth3'; // ID가 중복되지 않도록 확인 필요\r\n");
      out.write("				newSelect.setAttribute('onchange', 'ThirdDepth()');\r\n");
      out.write("\r\n");
      out.write("				// Add default option\r\n");
      out.write("                var defaultOption = document.createElement('option');\r\n");
      out.write("                defaultOption.value = 0;\r\n");
      out.write("                defaultOption.textContent = '카테고리 선택';\r\n");
      out.write("                newSelect.appendChild(defaultOption);\r\n");
      out.write("				\r\n");
      out.write("				// Add options based on response\r\n");
      out.write("				response.forEach(function(category) {\r\n");
      out.write("					var option = document.createElement('option');\r\n");
      out.write("					option.value = category.category_id;\r\n");
      out.write("					option.textContent = category.category_name;\r\n");
      out.write("					newSelect.appendChild(option);\r\n");
      out.write("				});\r\n");
      out.write("\r\n");
      out.write("				// categoryContainer에 새로운 <select> 추가\r\n");
      out.write("				var categoryContainer = document\r\n");
      out.write("						.querySelector('.categoryContainer');\r\n");
      out.write("				categoryContainer.appendChild(newSelect);\r\n");
      out.write("			},\r\n");
      out.write("			error : function(xhr, status, error) {\r\n");
      out.write("				console.error('AJAX 오류:', status, error);\r\n");
      out.write("			}\r\n");
      out.write("		})\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function ThirdDepth() {\r\n");
      out.write("		var selectedValue = document.getElementById(\"depth3\").value;\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type : 'POST',\r\n");
      out.write("			url : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/seller/find4thCategoryList.do',\r\n");
      out.write("			contentType : 'application/json',\r\n");
      out.write("			data : JSON.stringify(selectedValue),\r\n");
      out.write("			success : function(response) {\r\n");
      out.write("				console.log(response);\r\n");
      out.write("				//location.reload();\r\n");
      out.write("				\r\n");
      out.write("				// depth4 요소가 이미 존재하는 경우 제거\r\n");
      out.write("				var existingSelect = document.getElementById('depth4');\r\n");
      out.write("				if (existingSelect) {\r\n");
      out.write("					existingSelect.remove();\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("				//case 1. response가 비어있는 경우 >> 3단계가 마지막 선택항목임\r\n");
      out.write("				if(response.length===0){\r\n");
      out.write("					document.getElementById('depth3').setAttribute('name', 'finalCategory');\r\n");
      out.write("				}else{//case 2. response가 비어있지 않은 경우 >> 해당 항목은 4단계 선택지가 있음\r\n");
      out.write("					\r\n");
      out.write("					// 새로운 <select> 요소 depth4 생성\r\n");
      out.write("					var newSelect = document.createElement('select');\r\n");
      out.write("					newSelect.className = 'prdCategory';\r\n");
      out.write("					newSelect.id = 'depth4'; // ID가 중복되지 않도록 확인 필요\r\n");
      out.write("					//newSelect.setAttribute('onchange', 'FourthDepth()');\r\n");
      out.write("					newSelect.setAttribute('name', 'finalCategory');\r\n");
      out.write("					\r\n");
      out.write("					// Add default option\r\n");
      out.write("	                var defaultOption = document.createElement('option');\r\n");
      out.write("	                defaultOption.value = 0;\r\n");
      out.write("	                defaultOption.textContent = '카테고리 선택';\r\n");
      out.write("	                newSelect.appendChild(defaultOption);\r\n");
      out.write("\r\n");
      out.write("					// Add options based on response\r\n");
      out.write("					response.forEach(function(category) {\r\n");
      out.write("						var option = document.createElement('option');\r\n");
      out.write("						option.value = category.category_id;\r\n");
      out.write("						option.textContent = category.category_name;\r\n");
      out.write("						newSelect.appendChild(option);\r\n");
      out.write("					});\r\n");
      out.write("\r\n");
      out.write("					// categoryContainer에 새로운 <select> 추가\r\n");
      out.write("					var categoryContainer = document\r\n");
      out.write("							.querySelector('.categoryContainer');\r\n");
      out.write("					categoryContainer.appendChild(newSelect);\r\n");
      out.write("				\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("			},\r\n");
      out.write("			error : function(xhr, status, error) {\r\n");
      out.write("				console.error('AJAX 오류:', status, error);\r\n");
      out.write("			}\r\n");
      out.write("		})\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("	<div class=\"header_top inner\">\r\n");
      out.write("		<div class=\"leftGnb\">\r\n");
      out.write("			<h1 class=\"logo\">\r\n");
      out.write("				<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">\r\n");
      out.write("					<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/logo_main.png\" alt=\"메인로고\">\r\n");
      out.write("				</a>\r\n");
      out.write("			</h1>\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("			<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\" class=\"search_form\">\r\n");
      out.write("				<label for=\"search_wrap\"> \r\n");
      out.write("					<input name=\"search_input\" type=\"search\" /> \r\n");
      out.write("					<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/icon_serch.png\" alt=\"돋보기 아이콘\" class=\"search_img\" />\r\n");
      out.write("				</label>\r\n");
      out.write("			</form>\r\n");
      out.write("		</div> \r\n");
      out.write("		<div class=\"rightGnb\">  \r\n");
      out.write("			<ul>\r\n");
      out.write("				");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				<li>\r\n");
      out.write("					<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/customer/myPage.do\">\r\n");
      out.write("						<p>마이페이지</p>\r\n");
      out.write("						<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/icon-person2.png\" alt=\"마이페이지\" class=\"myPageIcon\">\r\n");
      out.write("					</a>\r\n");
      out.write("					");
      out.write("\r\n");
      out.write("					");
      out.write("\r\n");
      out.write("				</li>\r\n");
      out.write("				<li>\r\n");
      out.write("					<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cart/cart.do\">\r\n");
      out.write("						<p>장바구니</p>\r\n");
      out.write("						<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/icon-cart.png\" alt=\"장바구니\">\r\n");
      out.write("					</a>\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("	\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"header_bottom\">\r\n");
      out.write("		<div class=\"menu_wrap inner\">\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("			<ul class=\"left_menu\">\r\n");
      out.write("				<li data-menu=\"0\">\r\n");
      out.write("					<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/prod/productlist?shwCtgNum=11000000\"\r\n");
      out.write("					class=\"category_name\">여성</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li data-menu=\"1\">\r\n");
      out.write("					<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/prod/productlist?shwCtgNum=14000000\"\r\n");
      out.write("					class=\"category_name\">남성</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li data-menu=\"2\">\r\n");
      out.write("					<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/prod/productlist?shwCtgNum=13000000\"\r\n");
      out.write("					class=\"category_name\">키즈</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li data-menu=\"3\">\r\n");
      out.write("					<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/prod/productlist?shwCtgNum=15000000\"\r\n");
      out.write("					class=\"category_name\">럭셔리</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li data-menu=\"4\">\r\n");
      out.write("					<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/prod/productlist?shwCtgNum=12000000\"\r\n");
      out.write("					class=\"category_name\">스포츠</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li data-menu=\"5\">\r\n");
      out.write("					<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/prod/productlist?shwCtgNum=10000000\"\r\n");
      out.write("					class=\"category_name\">가방＆신발</a>\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("			<ul class=\"right_menu\">\r\n");
      out.write("				<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/customer/coordination.do\" class=\"highlight\">AI추천코디</a></li>\r\n");
      out.write("				<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/customer/productlist\" class=\"highlight\">옷대여</a></li>\r\n");
      out.write("				<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/adminqna/myqna.do\">Q&A</a></li>\r\n");
      out.write("				<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/notice/notices\">공지사항</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("		<div class=\"menu-backgorund\"></div>\r\n");
      out.write("		<div class=\"menu_pan inner\">\r\n");
      out.write("			<div class=\"dropdown_nav\">\r\n");
      out.write("\r\n");
      out.write("				<ul ctg=\"women\">\r\n");
      out.write("				</ul>\r\n");
      out.write("				<ul ctg=\"men\">\r\n");
      out.write("				</ul>\r\n");
      out.write("				<ul ctg=\"kids\">\r\n");
      out.write("				</ul>\r\n");
      out.write("				<ul ctg=\"luxury\">\r\n");
      out.write("				</ul>\r\n");
      out.write("				<ul ctg=\"sports\">\r\n");
      out.write("				</ul>\r\n");
      out.write("				<ul ctg=\"bagAndShoes\">\r\n");
      out.write("				</ul>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</header>\r\n");
      out.write("<script>\r\n");
      out.write("	$(function() {\r\n");
      out.write("		//$.noConflict(); //제이쿼리 충돌방지\r\n");
      out.write("		//메뉴 드롭 다운\r\n");
      out.write("		var isFirstHover = true; // 처음 마우스를 올리는지 여부를 추적\r\n");
      out.write("\r\n");
      out.write("		$(\".left_menu > li\").on(\"mouseenter\", function() {\r\n");
      out.write("			var menuIndex = $(this).data(\"menu\"); // data-menu 속성 값을 가져옴\r\n");
      out.write("			\r\n");
      out.write("	        $(\".left_menu > li\").css({\r\n");
      out.write("	            \"color\": \"#ccc\",\r\n");
      out.write("	            \"font-weight\": \"normal\"\r\n");
      out.write("	        }); // 모든 li를 #ccc 색상으로 변경하고 폰트 두께를 정상으로 설정\r\n");
      out.write("	        $(this).css({\r\n");
      out.write("	            \"color\": \"black\",\r\n");
      out.write("	            \"font-weight\": \"bold\"\r\n");
      out.write("	        }); // 호버한 li만 검정색으로 변경하고 폰트 두께를 두껍게 설정\r\n");
      out.write("			\r\n");
      out.write("			if (isFirstHover) {\r\n");
      out.write("				$(\".dropdown_nav ul\").stop().animate({\r\n");
      out.write("					height : \"0\"\r\n");
      out.write("				}, 500); // 모든 서브메뉴 높이 0으로 설정\r\n");
      out.write("				$(\".dropdown_nav ul\").eq(menuIndex).stop().animate({\r\n");
      out.write("					height : \"400px\"\r\n");
      out.write("				}, 500);\r\n");
      out.write("				$(\".dropdown_nav\").stop().animate({\r\n");
      out.write("					height : \"400px\"\r\n");
      out.write("				}, 500); // 서브메뉴 표시\r\n");
      out.write("	            $(\".menu-backgorund\").css(\"display\",\"block\");\r\n");
      out.write("				\r\n");
      out.write("				isFirstHover = false; // 이후 마우스 이동 시 애니메이션 제거\r\n");
      out.write("			} else {\r\n");
      out.write("				$(\".dropdown_nav ul\").css(\"height\", \"0\"); // 모든 서브메뉴 높이 0으로 설정\r\n");
      out.write("				$(\".dropdown_nav ul\").eq(menuIndex).css(\"height\", \"400px\");\r\n");
      out.write("				$(\".dropdown_nav\").css(\"height\", \"400px\"); // 서브메뉴 표시\r\n");
      out.write("	            $(\".menu-backgorund\").css(\"display\", \"blcok\"); // 배경 표시\r\n");
      out.write("	            \r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		$(\".dropdown_nav\").on(\"mouseleave\", function() {\r\n");
      out.write("		   $(\".left_menu > li\").css({\r\n");
      out.write("	            \"color\": \"black\",\r\n");
      out.write("	            \"font-weight\": \"normal\"\r\n");
      out.write("	        }); // 모든 li 색상을 기본으로 변경하고 폰트 두께를 정상으로 설정\r\n");
      out.write("			// 마우스가 떠났을 때 서브메뉴 높이 초기화\r\n");
      out.write("			$(\".dropdown_nav ul\").css(\"height\", \"0\");\r\n");
      out.write("			$(\".dropdown_nav\").css(\"height\", \"0\");\r\n");
      out.write("	        $(\".menu-backgorund\").css(\"display\",\"none\"); // 배경 숨김	\r\n");
      out.write("			isFirstHover = true; // 마우스를 떠났을 때 다시 애니메이션 활성화\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("		});\r\n");
      out.write("	\r\n");
      out.write("		var h_ctg = {\r\n");
      out.write("				'women':11000000,\r\n");
      out.write("				'men':14000000,\r\n");
      out.write("				'kids':13000000,\r\n");
      out.write("				'luxury':15000000,\r\n");
      out.write("				'sports':12000000,\r\n");
      out.write("				'bagAndShoes':10000000\r\n");
      out.write("		}\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/prod/headerctg\",\r\n");
      out.write("			type:'post',\r\n");
      out.write("			data:JSON.stringify(h_ctg),\r\n");
      out.write("			dataType: \"json\",\r\n");
      out.write("			contentType:\"application/json\",\r\n");
      out.write("			success: function(ctgMap) {\r\n");
      out.write("				for(var key in ctgMap) {\r\n");
      out.write("					$('.dropdown_nav').find(`ul[ctg='${key}']`).append(`<li><a href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/prod/productlist?shwCtgNum=${ctgMap[key][0].parent_category_id}'>전체 상품</a></li>`);\r\n");
      out.write("					$(ctgMap[key]).each(function(index, ctgVO) {\r\n");
      out.write("						$('.dropdown_nav').find(`ul[ctg='${key}']`).append(`<li><a href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/prod/productlist?shwCtgNum=${ctgVO.category_id}'>${ctgVO.category_name}</a></li>`);\r\n");
      out.write("					});\r\n");
      out.write("				}\r\n");
      out.write("			},\r\n");
      out.write("			error: function() {\r\n");
      out.write("				\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("	<main>\r\n");
      out.write("		<aside>\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li><a onclick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/seller/MainPage.do'\">통계</a></li>\r\n");
      out.write("				<li><a onclick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/seller/PrdList.do'\">판매/대여\r\n");
      out.write("						상품 목록</a></li>\r\n");
      out.write("				<li><a onclick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/seller/DeliveryList.do'\">주문/배송</a></li>\r\n");
      out.write("				<li><a onclick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/seller/Q&AList.do'\">문의\r\n");
      out.write("						목록</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</aside>\r\n");
      out.write("		<section>\r\n");
      out.write("			<h2>마이페이지</h2>\r\n");
      out.write("			<hr />\r\n");
      out.write("			<div class=\"user-info\">\r\n");
      out.write("				<p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sellerInfo.member_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("				<p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sellerInfo.member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("				<h1>상품 정보 수정</h1>\r\n");
      out.write("				<form method=\"post\" action=\"/shoppingmall/seller/modifyPrdouct\"\r\n");
      out.write("					enctype=\"multipart/form-data\" accept-charset=\"UTF-8\">\r\n");
      out.write("					\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<label style=\"display: inline-block; width: 100px;\">상품ID</label>\r\n");
      out.write("						<input class=\"unchangedInput\" type=\"text\" name=\"prdId\"\r\n");
      out.write("							value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ProductInfo.prod_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<label style=\"display: inline-block; width: 100px;\">상품명</label>\r\n");
      out.write("						<input class=\"unchangedInput\" type=\"text\" name=\"prdName\"\r\n");
      out.write("							value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ProductInfo.prod_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<label style=\"display: inline-block; width: 100px;\">가격</label>\r\n");
      out.write("						<input id=\"prdPrice\" type=\"number\" name=\"prdPrice\"\r\n");
      out.write("							value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ProductInfo.prod_price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("						<label style=\"display: inline-block; width: 100px;\">원</label>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					<!-- 카테고리 -->\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<label style=\"display: inline-block; width: 100px;\">카테고리</label>\r\n");
      out.write("						<p class=\"category\" style=\"display: inline-block; margin: 0;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${CategoryInfo.category_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("						<div class=\"categoryContainer\">\r\n");
      out.write("							<select class=\"prdCategory\" id=\"depth1\" onchange=\"firstDepth()\">\r\n");
      out.write("								<option value=0>선택 안함</option>\r\n");
      out.write("								");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("							</select>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<!-- 메인 사진 미리보기 구역 : DB 및 서버 저장소에 등록되어 있는 사진 파일들을 미리보기로 보여준다 -->\r\n");
      out.write("					<div id=\"prdMainImgPreview\">\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label style=\"display: inline-block; width: 100px;\">메인 사진목록</label>\r\n");
      out.write("							<button type=\"button\" id=\"addImageBtn\" onclick=\"resetMainProdImg()\">사진 항목 초기화</button>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div id=\"prdMainImgFileContainer\">\r\n");
      out.write("							");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					<!-- 메인 사진 추가 구역 : 사진 재등록을 선택하면 활성화 & 화면에 표시됨 -->\r\n");
      out.write("					<div id=\"mainImgSection\" class=\"hidden\">\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label style=\"display: inline-block; width: 100px;\">메인사진</label>\r\n");
      out.write("							<button type=\"button\" id=\"addImageBtn\" onclick=\"addMainImgFile()\">사진 추가</button>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div id=\"prdMainImgFileContainer\"></div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<!-- 설명 사진 미리보기 구역 : DB 및 서버 저장소에 등록되어 있는 사진 파일들을 미리보기로 보여준다 -->\r\n");
      out.write("					<div id=\"prdDescImgPreview\">\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label style=\"display: inline-block; width: 100px;\">설명 사진목록</label>\r\n");
      out.write("							<button type=\"button\" id=\"addImageBtn\" onclick=\"resetDescProdImg()\">사진 항목 초기화</button>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div id=\"prdDescImgFileContainer\">\r\n");
      out.write("							");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					<!-- 설명 사진 추가 구역 : 사진 재등록을 선택하면 활성화 & 화면에 표시됨 -->\r\n");
      out.write("					<div id=\"descImgSection\" class=\"hidden\">\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label style=\"display: inline-block; width: 100px;\">상품 설명 사진 등록</label>\r\n");
      out.write("							<button type=\"button\" id=\"addImageBtn\" onclick=\"addDescImgFile()\">사진 추가</button>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div id=\"prdDescImgFileContainer\"></div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<label>상품설명</label>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<textarea rows=\"5\" id=\"prdDescription\" name=\"prdDescription\">\r\n");
      out.write("						");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ProductInfo.prod_desc}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					<hr>\r\n");
      out.write("					\r\n");
      out.write("					<h1>판매용 재고 정보 조회 / 재고 수정</h1>\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<label style=\"display: inline-block; width: 100px;\">재고명</label>\r\n");
      out.write("						<input class=\"unchangedInput\" type=\"text\" name=\"stockid\"\r\n");
      out.write("							value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${StockInfo.s_stock_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<label>해당 재고의 옵션 목록</label>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"optionList\" id=\"optionList\">\r\n");
      out.write("						<table id=\"optionTable\">\r\n");
      out.write("							<thead>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<th>옵션명</th>\r\n");
      out.write("									<th>옵션값</th>\r\n");
      out.write("								</tr>\r\n");
      out.write("							</thead>\r\n");
      out.write("							<tbody>\r\n");
      out.write("								");
      if (_jspx_meth_c_005fforEach_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("							</tbody>\r\n");
      out.write("						</table>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<label style=\"display: inline-block; width: 100px;\">재고량</label>\r\n");
      out.write("						<input id=\"prdPrice\" type=\"number\" name=\"prdStock\" value = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${StockInfo.stock}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("						<label style=\"display: inline-block; width: 100px;\">개</label>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"buttons\">\r\n");
      out.write("						<button type=\"submit\">수정하기</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("	</main>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/seller/seller_SellStock_modifyPrd.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path");
      // /WEB-INF/views/seller/seller_SellStock_modifyPrd.jsp(4,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/seller/seller_SellStock_modifyPrd.jsp(4,0) '${pageContext.servletContext.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.servletContext.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /WEB-INF/views/seller/../common/header.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("path");
      // /WEB-INF/views/seller/../common/header.jsp(4,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/seller/../common/header.jsp(4,0) '${pageContext.servletContext.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.servletContext.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f2_reused = false;
    try {
      _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f2.setParent(null);
      // /WEB-INF/views/seller/../common/header.jsp(7,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setVar("isLoggedIn");
      // /WEB-INF/views/seller/../common/header.jsp(7,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/seller/../common/header.jsp(7,0) '${not empty sessionScope.member}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${not empty sessionScope.member}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
      if (_jspx_th_c_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
      _jspx_th_c_005fset_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("					");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("					");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/seller/../common/header.jsp(30,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${isLoggedIn}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("						<li>\r\n");
          out.write("							<a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member_test/logout.do\"> \r\n");
          out.write("								<p>로그아웃</p>\r\n");
          out.write("								<img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/images/icon-logout.png\" alt=\"로그아웃\">\r\n");
          out.write("							</a>\r\n");
          out.write("						</li>\r\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("						<li>\r\n");
          out.write("							<a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member_test/login.do\" id=\"loginLink\"> \r\n");
          out.write("								<p>로그인</p>\r\n");
          out.write("								<img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/images/icon-login.gif\" alt=\"로그인\">\r\n");
          out.write("							</a>\r\n");
          out.write("						</li>\r\n");
          out.write("						<li>\r\n");
          out.write("							<a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member_test/signup\">\r\n");
          out.write("								<p>회원가입</p>\r\n");
          out.write("								<img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/images/icon-sign-in.png\" alt=\"회원가입\">\r\n");
          out.write("							</a>\r\n");
          out.write("						</li>\r\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/seller/seller_SellStock_modifyPrd.jsp(418,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("category1");
      // /WEB-INF/views/seller/seller_SellStock_modifyPrd.jsp(418,8) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/seller/seller_SellStock_modifyPrd.jsp(418,8) '${depth1categoryList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${depth1categoryList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("									<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category1.category_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category1.category_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("								");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/views/seller/seller_SellStock_modifyPrd.jsp(432,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("mainImgName");
      // /WEB-INF/views/seller/seller_SellStock_modifyPrd.jsp(432,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/seller/seller_SellStock_modifyPrd.jsp(432,7) '${ProdMainImgList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${ProdMainImgList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("								<img src=\"http://localhost:9090/saren/ProdImgFile/main/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mainImgName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\r\n");
            out.write("									width=\"200\" height=\"200\">\r\n");
            out.write("							");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f2_reused = false;
    try {
      _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f2.setParent(null);
      // /WEB-INF/views/seller/seller_SellStock_modifyPrd.jsp(455,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVar("imgName");
      // /WEB-INF/views/seller/seller_SellStock_modifyPrd.jsp(455,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/seller/seller_SellStock_modifyPrd.jsp(455,7) '${ProdDescImgList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${ProdDescImgList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
        if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("								<img\r\n");
            out.write("									src=\"http://localhost:9090/saren/ProdImgFile/desc/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${imgName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\r\n");
            out.write("									width=\"200\" height=\"200\">\r\n");
            out.write("							");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
      _jspx_th_c_005fforEach_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f3 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f3_reused = false;
    try {
      _jspx_th_c_005fforEach_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f3.setParent(null);
      // /WEB-INF/views/seller/seller_SellStock_modifyPrd.jsp(501,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f3.setVar("option");
      // /WEB-INF/views/seller/seller_SellStock_modifyPrd.jsp(501,8) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f3.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/seller/seller_SellStock_modifyPrd.jsp(501,8) '${optionList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${optionList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f3 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f3 = _jspx_th_c_005fforEach_005f3.doStartTag();
        if (_jspx_eval_c_005fforEach_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("									<tr>\r\n");
            out.write("										<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${option.opt_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("										<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${option.opt_value}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("									</tr>\r\n");
            out.write("								");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f3.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f3[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f3.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f3.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f3);
      _jspx_th_c_005fforEach_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f3_reused);
    }
    return false;
  }
}
