/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-07-08 23:46:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.customer;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class myInfoUpdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/sh3/workspace-sts-3.9.18/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Shinhan_SW_1st_TeamProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/customer/../common/header.jsp", Long.valueOf(1720433011362L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1719295440415L));
    _jspx_dependants.put("/WEB-INF/views/customer/../common/footer.jsp", Long.valueOf(1720324748694L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>마이페이지-회원정보수정</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/mypage.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/header_footer.css\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery-3.7.1.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("    .overlay {\r\n");
      out.write("        display: none;\r\n");
      out.write("        position: fixed;\r\n");
      out.write("        top: 0;\r\n");
      out.write("        left: 0;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        background: rgba(0, 0, 0, 0.5);\r\n");
      out.write("        z-index: 999;\r\n");
      out.write("    }\r\n");
      out.write("	#addrAdd_wrap{\r\n");
      out.write("		display: none; \r\n");
      out.write("	}\r\n");
      out.write("	#addrAddForm {\r\n");
      out.write("	    z-index: 1000;\r\n");
      out.write("	    background-color: #fefefe;\r\n");
      out.write("	    margin: 0 auto;\r\n");
      out.write("	    padding: 20px;\r\n");
      out.write("	    border: 1px solid #888;\r\n");
      out.write("	    width: 70%;\r\n");
      out.write("	    padding: 70px 20px;\r\n");
      out.write("	    max-width: 600px;\r\n");
      out.write("	    position: fixed;\r\n");
      out.write("	    top: 50%;\r\n");
      out.write("	    left: 50%;\r\n");
      out.write("	    transform: translate(-50%, -50%);\r\n");
      out.write("        border-radius: 30px;\r\n");
      out.write("	}\r\n");
      out.write("	#addrAddForm>h1{\r\n");
      out.write("		padding-bottom: 10px;\r\n");
      out.write("	}\r\n");
      out.write("    label {\r\n");
      out.write("        display: block;\r\n");
      out.write("        margin-bottom: 5px;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("    }\r\n");
      out.write("    input[type=\"text\"], input[type=\"tel\"] {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        padding: 10px;\r\n");
      out.write("        margin-bottom: 15px;\r\n");
      out.write("        border: 1px solid #ccc;\r\n");
      out.write("        border-radius: 4px;\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("    }\r\n");
      out.write("    #searchPostcode {\r\n");
      out.write("        padding: 10px 15px;\r\n");
      out.write("        border: 1px solid #ccc;\r\n");
      out.write("        background-color: #f1f1f1;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("    #submitBtn {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        padding: 10px;\r\n");
      out.write("        background-color: #513AE4;\r\n");
      out.write("        color: white;\r\n");
      out.write("        border: none;\r\n");
      out.write("        border-radius: 6px;\r\n");
      out.write("	    cursor: pointer;\r\n");
      out.write("	    margin-top: 30px;\r\n");
      out.write("	    font-size: 18px;\r\n");
      out.write("	    font-weight: bold;\r\n");
      out.write("    }\r\n");
      out.write("    #submitBtn:hover {\r\n");
      out.write("        background-color: #513AE4;\r\n");
      out.write("       \r\n");
      out.write("    }\r\n");
      out.write("    .info {\r\n");
      out.write("        font-size: 0.9em;\r\n");
      out.write("        color: gray;\r\n");
      out.write("        margin-bottom: 15px;\r\n");
      out.write("    }\r\n");
      out.write("    .close {\r\n");
      out.write("        position: absolute;\r\n");
      out.write("	    right: 20px;\r\n");
      out.write("	    top: 10px;\r\n");
      out.write("	    font-size: 30px;\r\n");
      out.write("	    font-weight: bold;\r\n");
      out.write("	    color: #aaa;\r\n");
      out.write("	    cursor: pointer;\r\n");
      out.write("	}\r\n");
      out.write("	.close:hover,\r\n");
      out.write("	.close:focus {\r\n");
      out.write("	    color: #513AE4;\r\n");
      out.write("	    text-decoration: none;\r\n");
      out.write("	    cursor: pointer;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	$(function() {\r\n");
      out.write("         $('#addrAddButton').click(function() {\r\n");
      out.write("             $('.overlay, #addrAdd_wrap').show();\r\n");
      out.write("         });\r\n");
      out.write("\r\n");
      out.write("         $('.close').click(function() {\r\n");
      out.write("             $('.overlay, #addrAdd_wrap').hide();\r\n");
      out.write("         });\r\n");
      out.write("\r\n");
      out.write("         $(window).click(function(event) {\r\n");
      out.write("             if ($(event.target).is('.overlay')) {\r\n");
      out.write("                 $('.overlay, #addrAdd_wrap').hide();\r\n");
      out.write("             }\r\n");
      out.write("         });\r\n");
      out.write("         \r\n");
      out.write("         //클릭한 주소 목록 삭제  \r\n");
      out.write("         $('.delete-btn').click(function(e) {\r\n");
      out.write("        	 e.preventDefault();\r\n");
      out.write("        	 \r\n");
      out.write("        	 // 클릭된 버튼의 부모 요소인 address-box를 찾음\r\n");
      out.write("       		 var addressBoxWrap = $(this).parent('.address-box-wrap');\r\n");
      out.write("        	 var addr_num = addressBoxWrap.find('.address-box').find('input[type=\"hidden\"]').val();\r\n");
      out.write("        	 console.log('삭제할 주소 번호: ' + addr_num);\r\n");
      out.write("       	    \r\n");
      out.write("       	 	 // 현재 address-box의 개수를 계산\r\n");
      out.write("       	     var addressBoxCount = $('.address-box').length;\r\n");
      out.write("       	     console.log('현재 address-box 개수: ' + addressBoxCount);\r\n");
      out.write("       	     \r\n");
      out.write("       	     // masterCheck 값을 확인 (여기서는 #masterTest 요소의 텍스트 값)\r\n");
      out.write("       	     var masterCheck = $('#masterTest').text().trim();\r\n");
      out.write("       	     console.log('masterCheck 값: ' + masterCheck);\r\n");
      out.write("       	          \r\n");
      out.write("       	     \r\n");
      out.write("	       	  // '대표' 주소인지 확인하여 삭제를 막음\r\n");
      out.write("	       	  if (masterCheck == \"대표\") {\r\n");
      out.write("	       	        alert(\"대표 주소는 삭제할 수 없습니다.\");\r\n");
      out.write("	       	        //location.reload();\r\n");
      out.write("	       	        return \r\n");
      out.write("	       	    }\r\n");
      out.write("       	  \r\n");
      out.write("       	    \r\n");
      out.write("	       	    // 삭제 요청을 위한 데이터\r\n");
      out.write("	       	    var addrData = {\r\n");
      out.write("	       	        addr_num: addr_num\r\n");
      out.write("	       	    };\r\n");
      out.write("	       	    console.log(addrData);\r\n");
      out.write("	       \r\n");
      out.write("	       	    // 주소가 1개 이상일 때만 삭제 요청\r\n");
      out.write("	       	    if (addressBoxCount > 1) {\r\n");
      out.write("		       	    // 확인 절차 추가\r\n");
      out.write("		       	    if (!confirm(\"정말로 이 주소를 삭제하시겠습니까?\")) {\r\n");
      out.write("		       	        return;\r\n");
      out.write("		       	    }\r\n");
      out.write("		       	    \r\n");
      out.write("					$.ajax({\r\n");
      out.write("		                url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/customer/myAddrDelete.do\",\r\n");
      out.write("		                type: \"POST\",\r\n");
      out.write("		                contentType: 'application/json',\r\n");
      out.write("		                data: JSON.stringify(addrData),\r\n");
      out.write("		                success: function(resultData) {\r\n");
      out.write("		                	\r\n");
      out.write("		                	if(resultData == 1){\r\n");
      out.write("		 	                    //$(\".resultText_here\").text(\"삭제되었습니다.\"); //아직 css 없음\r\n");
      out.write("		 	                    alert(\"배송지가 삭제되었습니다.\");\r\n");
      out.write("		 	                    location.reload();\r\n");
      out.write("		                	}else{\r\n");
      out.write("		                		//$(\".resultText_here\").test(\"오류가 발생했습니다. 다시 시도해주세요.\");\r\n");
      out.write("		 	                    alert(\"오류가 발생했습니다. 다시 시도해주세요.\");\r\n");
      out.write("		                	}\r\n");
      out.write("		                	\r\n");
      out.write("		                },\r\n");
      out.write("		                error: function(xhr, status, error) {\r\n");
      out.write("		                    console.error(\"Error: \" + error);\r\n");
      out.write("		                    //$(\".resultText_here\").text(\"서버 오류가 발생했습니다. 다시 시도해주세요.\");\r\n");
      out.write("		                }\r\n");
      out.write("		            });\r\n");
      out.write("	       	    } else {\r\n");
      out.write("	       	        alert(\"주소는 1개 이상 존재해야 합니다.\");\r\n");
      out.write("	       	    }\r\n");
      out.write("					\r\n");
      out.write("			 });\r\n");
      out.write("       \r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("	<div class=\"header_top inner\">\r\n");
      out.write("		<div class=\"leftGnb\">\r\n");
      out.write("			<h1 class=\"logo\">\r\n");
      out.write("				<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">\r\n");
      out.write("					<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/logo_main.png\" alt=\"메인로고\">\r\n");
      out.write("				</a>\r\n");
      out.write("			</h1>\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("			<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\" class=\"search_form\">\r\n");
      out.write("				<label for=\"search_wrap\"> \r\n");
      out.write("					<input name=\"search_input\" type=\"search\" /> \r\n");
      out.write("					<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/icon_serch.png\" alt=\"돋보기 아이콘\" class=\"search_img\" />\r\n");
      out.write("				</label>\r\n");
      out.write("			</form>\r\n");
      out.write("		</div> \r\n");
      out.write("		<div class=\"rightGnb\">  \r\n");
      out.write("			<ul>\r\n");
      out.write("				");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				<li>\r\n");
      out.write("					<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/customer/myPage.do\">\r\n");
      out.write("						<p>마이페이지</p>\r\n");
      out.write("						<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/icon-person2.png\" alt=\"마이페이지\" class=\"myPageIcon\">\r\n");
      out.write("					</a>\r\n");
      out.write("					");
      out.write("\r\n");
      out.write("					");
      out.write("\r\n");
      out.write("				</li>\r\n");
      out.write("				<li>\r\n");
      out.write("					<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cart/cart.do\">\r\n");
      out.write("						<p>장바구니</p>\r\n");
      out.write("						<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/icon-cart.png\" alt=\"장바구니\">\r\n");
      out.write("					</a>\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("	\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"header_bottom\">\r\n");
      out.write("		<div class=\"menu_wrap inner\">\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("			<ul class=\"left_menu\">\r\n");
      out.write("				<li data-menu=\"0\">\r\n");
      out.write("					<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/prod/productlist?shwCtgNum=11000000\"\r\n");
      out.write("					class=\"category_name\">여성</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li data-menu=\"1\">\r\n");
      out.write("					<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/prod/productlist?shwCtgNum=14000000\"\r\n");
      out.write("					class=\"category_name\">남성</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li data-menu=\"2\">\r\n");
      out.write("					<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/prod/productlist?shwCtgNum=13000000\"\r\n");
      out.write("					class=\"category_name\">키즈</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li data-menu=\"3\">\r\n");
      out.write("					<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/prod/productlist?shwCtgNum=15000000\"\r\n");
      out.write("					class=\"category_name\">럭셔리</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li data-menu=\"4\">\r\n");
      out.write("					<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/prod/productlist?shwCtgNum=12000000\"\r\n");
      out.write("					class=\"category_name\">스포츠</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li data-menu=\"5\">\r\n");
      out.write("					<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/prod/productlist?shwCtgNum=10000000\"\r\n");
      out.write("					class=\"category_name\">가방＆신발</a>\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("			<ul class=\"right_menu\">\r\n");
      out.write("				<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/customer/coordination.do\" class=\"highlight\">AI추천코디</a></li>\r\n");
      out.write("				<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/customer/productlist\" class=\"highlight\">옷대여</a></li>\r\n");
      out.write("				<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/adminqna/myqna.do\">Q&A</a></li>\r\n");
      out.write("				<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/notice/notices\">공지사항</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("		<div class=\"menu-backgorund\"></div>\r\n");
      out.write("		<div class=\"menu_pan inner\">\r\n");
      out.write("			<div class=\"dropdown_nav\">\r\n");
      out.write("\r\n");
      out.write("				<ul ctg=\"women\">\r\n");
      out.write("				</ul>\r\n");
      out.write("				<ul ctg=\"men\">\r\n");
      out.write("				</ul>\r\n");
      out.write("				<ul ctg=\"kids\">\r\n");
      out.write("				</ul>\r\n");
      out.write("				<ul ctg=\"luxury\">\r\n");
      out.write("				</ul>\r\n");
      out.write("				<ul ctg=\"sports\">\r\n");
      out.write("				</ul>\r\n");
      out.write("				<ul ctg=\"bagAndShoes\">\r\n");
      out.write("				</ul>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</header>\r\n");
      out.write("<script>\r\n");
      out.write("	$(function() {\r\n");
      out.write("		//$.noConflict(); //제이쿼리 충돌방지\r\n");
      out.write("		//메뉴 드롭 다운\r\n");
      out.write("		var isFirstHover = true; // 처음 마우스를 올리는지 여부를 추적\r\n");
      out.write("\r\n");
      out.write("		$(\".left_menu > li\").on(\"mouseenter\", function() {\r\n");
      out.write("			var menuIndex = $(this).data(\"menu\"); // data-menu 속성 값을 가져옴\r\n");
      out.write("			\r\n");
      out.write("	        $(\".left_menu > li\").css({\r\n");
      out.write("	            \"color\": \"#ccc\",\r\n");
      out.write("	            \"font-weight\": \"normal\"\r\n");
      out.write("	        }); // 모든 li를 #ccc 색상으로 변경하고 폰트 두께를 정상으로 설정\r\n");
      out.write("	        $(this).css({\r\n");
      out.write("	            \"color\": \"black\",\r\n");
      out.write("	            \"font-weight\": \"bold\"\r\n");
      out.write("	        }); // 호버한 li만 검정색으로 변경하고 폰트 두께를 두껍게 설정\r\n");
      out.write("			\r\n");
      out.write("			if (isFirstHover) {\r\n");
      out.write("				$(\".dropdown_nav ul\").stop().animate({\r\n");
      out.write("					height : \"0\"\r\n");
      out.write("				}, 500); // 모든 서브메뉴 높이 0으로 설정\r\n");
      out.write("				$(\".dropdown_nav ul\").eq(menuIndex).stop().animate({\r\n");
      out.write("					height : \"400px\"\r\n");
      out.write("				}, 500);\r\n");
      out.write("				$(\".dropdown_nav\").stop().animate({\r\n");
      out.write("					height : \"400px\"\r\n");
      out.write("				}, 500); // 서브메뉴 표시\r\n");
      out.write("	            $(\".menu-backgorund\").css(\"display\",\"block\");\r\n");
      out.write("				\r\n");
      out.write("				isFirstHover = false; // 이후 마우스 이동 시 애니메이션 제거\r\n");
      out.write("			} else {\r\n");
      out.write("				$(\".dropdown_nav ul\").css(\"height\", \"0\"); // 모든 서브메뉴 높이 0으로 설정\r\n");
      out.write("				$(\".dropdown_nav ul\").eq(menuIndex).css(\"height\", \"400px\");\r\n");
      out.write("				$(\".dropdown_nav\").css(\"height\", \"400px\"); // 서브메뉴 표시\r\n");
      out.write("	            $(\".menu-backgorund\").css(\"display\", \"blcok\"); // 배경 표시\r\n");
      out.write("	            \r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		$(\".dropdown_nav\").on(\"mouseleave\", function() {\r\n");
      out.write("		   $(\".left_menu > li\").css({\r\n");
      out.write("	            \"color\": \"black\",\r\n");
      out.write("	            \"font-weight\": \"normal\"\r\n");
      out.write("	        }); // 모든 li 색상을 기본으로 변경하고 폰트 두께를 정상으로 설정\r\n");
      out.write("			// 마우스가 떠났을 때 서브메뉴 높이 초기화\r\n");
      out.write("			$(\".dropdown_nav ul\").css(\"height\", \"0\");\r\n");
      out.write("			$(\".dropdown_nav\").css(\"height\", \"0\");\r\n");
      out.write("	        $(\".menu-backgorund\").css(\"display\",\"none\"); // 배경 숨김	\r\n");
      out.write("			isFirstHover = true; // 마우스를 떠났을 때 다시 애니메이션 활성화\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("		});\r\n");
      out.write("	\r\n");
      out.write("		var h_ctg = {\r\n");
      out.write("				'women':11000000,\r\n");
      out.write("				'men':14000000,\r\n");
      out.write("				'kids':13000000,\r\n");
      out.write("				'luxury':15000000,\r\n");
      out.write("				'sports':12000000,\r\n");
      out.write("				'bagAndShoes':10000000\r\n");
      out.write("		}\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/prod/headerctg\",\r\n");
      out.write("			type:'post',\r\n");
      out.write("			data:JSON.stringify(h_ctg),\r\n");
      out.write("			dataType: \"json\",\r\n");
      out.write("			contentType:\"application/json\",\r\n");
      out.write("			success: function(ctgMap) {\r\n");
      out.write("				for(var key in ctgMap) {\r\n");
      out.write("					$('.dropdown_nav').find(`ul[ctg='${key}']`).append(`<li><a href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/prod/productlist?shwCtgNum=${ctgMap[key][0].parent_category_id}'>전체 상품</a></li>`);\r\n");
      out.write("					$(ctgMap[key]).each(function(index, ctgVO) {\r\n");
      out.write("						$('.dropdown_nav').find(`ul[ctg='${key}']`).append(`<li><a href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/prod/productlist?shwCtgNum=${ctgVO.category_id}'>${ctgVO.category_name}</a></li>`);\r\n");
      out.write("					});\r\n");
      out.write("				}\r\n");
      out.write("			},\r\n");
      out.write("			error: function() {\r\n");
      out.write("				\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("	<div class=\"overlay\"></div>\r\n");
      out.write("	<div>\r\n");
      out.write("		<p class=\"resultText_here\"></p>\r\n");
      out.write("	</div>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("    <div class=\"overlay\"></div>\r\n");
      out.write("	<div id=\"addrAdd_wrap\">\r\n");
      out.write("	    <form id=\"addrAddForm\">\r\n");
      out.write("	    	<h1>배송지 입력</h1>\r\n");
      out.write("			<span class=\"close\">&times;</span>\r\n");
      out.write("	        <label for=\"address\">주소 <span style=\"color: red;\">*</span></label>\r\n");
      out.write("\r\n");
      out.write("	        ");
      out.write("	\r\n");
      out.write("			<input type=\"text\" id=\"sample6_postcode\" placeholder=\"우편번호\" name=\"zipcode\" required=\"required\">\r\n");
      out.write("			<input type=\"button\" onclick=\"sample6_execDaumPostcode()\" value=\"우편번호 찾기\" id=\"searchPostcode\" required=\"required\"><br>\r\n");
      out.write("			<input type=\"text\" id=\"sample6_address\" placeholder=\"주소\" name=\"main_address\" required=\"required\"><br>\r\n");
      out.write("			<input type=\"text\" id=\"sample6_detailAddress\" placeholder=\"상세주소\" name=\"detail_address\" required=\"required\">\r\n");
      out.write("			<input type=\"text\" id=\"sample6_extraAddress\" placeholder=\"참고항목\" name=\"sub_address\">\r\n");
      out.write("			<br/>\r\n");
      out.write("			<span>대표주소 설정</span>\r\n");
      out.write("			<input type=\"checkbox\" name=\"is_master_addr\" id=\"isMasterAddr\">\r\n");
      out.write("			\r\n");
      out.write("	        <input type=\"button\" id=\"submitBtn\" value=\"확인\">\r\n");
      out.write("	    </form>\r\n");
      out.write("    </div>\r\n");
      out.write(" \r\n");
      out.write("	");
      out.write("\r\n");
      out.write("	<div class=\"mypage_wrap\">\r\n");
      out.write("		<div class=\"myinfo inner\">\r\n");
      out.write("			<nav>\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li>\r\n");
      out.write("						<h3>\r\n");
      out.write("							<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/customer/orderlist.do\">나의주문</a>\r\n");
      out.write("						</h3>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li>\r\n");
      out.write("						<h3>\r\n");
      out.write("							<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/customer/rentlist.do\">나의대여</a>\r\n");
      out.write("						</h3>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li>\r\n");
      out.write("						<h3>\r\n");
      out.write("							<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cart/cart.do\">장바구니</a>\r\n");
      out.write("						</h3>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li>\r\n");
      out.write("						<h3>\r\n");
      out.write("							<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/review/myreview.do\">나의글</a>\r\n");
      out.write("						</h3>\r\n");
      out.write("						<ul class=\"myinfo_submenu\">\r\n");
      out.write("							<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/adminqna/myqna.do\">문의글</a></li>\r\n");
      out.write("							<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/review/myreview.do\">리뷰</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li>\r\n");
      out.write("						<h3>\r\n");
      out.write("							<a href=\"javascript:#void\">회원정보</a>\r\n");
      out.write("						</h3>\r\n");
      out.write("						<ul class=\"myinfo_submenu\">\r\n");
      out.write("							<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/customer/myInfoUpdate.do\">정보수정</a></li>\r\n");
      out.write("							<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/customer/memberDelete.do\">회원탈퇴</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</nav>\r\n");
      out.write("			<div class=\"mypage_here\">\r\n");
      out.write("				<div class=\"section_wrap\">\r\n");
      out.write("					<h1 class=\"myinfo_title\">회원 정보 수정</h1>\r\n");
      out.write("					<div class=\"section myinfo_update\">\r\n");
      out.write("						<!-- \"비밀번호 확인\" 버튼 클릭: myinfo_update에서 페이지 업데이트 -->\r\n");
      out.write("						<div class=\"pw-check\">\r\n");
      out.write("							<p>회원님의 개인정보보호를 위한 본인 확인절차를 위해 비밀번호를 입력해 주세요.</p>\r\n");
      out.write("							<button id=\"loadButton\"\r\n");
      out.write("							 onclick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/customer/myInfoUpdateStep2.do'\" \r\n");
      out.write("							 class=\"button\" type=\"button\">비밀번호 확인</button>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<h2 class=\"myinfo_title\">나의 배송지</h2>\r\n");
      out.write("				<form id=\"addrListForm\" method=\"post\">\r\n");
      out.write("					<div class=\"section\">\r\n");
      out.write("						");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("						<div class=\"adress-add\">\r\n");
      out.write("							<button id=\"addrAddButton\" type=\"button\" class=\"button\">배송지 추가</button>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</form>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f3(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Footer Example</title>\r\n");
      out.write("<style>\r\n");
      out.write("main {\r\n");
      out.write("	flex: 1;\r\n");
      out.write("	/* main 요소가 남은 공간을 모두 차지하도록 합니다. 이렇게 하면 footer가 항상 페이지 하단에 위치하게 됩니다 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer {\r\n");
      out.write("	background-color: #333; /* 배경색을 어두운 회색으로 설정합니다 */\r\n");
      out.write("	color: white; /* 텍스트 색상을 흰색으로 설정합니다 */\r\n");
      out.write("	text-align: center; /* 텍스트를 가운데 정렬합니다 */\r\n");
      out.write("	padding: 20px 0; /* 위아래로 20px의 패딩을 추가합니다 */\r\n");
      out.write("	width: 100%; /* footer가 페이지 전체 너비를 차지하도록 합니다 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer .footer-line {\r\n");
      out.write("	margin: 10px 0; /* 위아래로 10px의 마진을 추가합니다 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer .footer-text {\r\n");
      out.write("	margin: 5px 0; /* 위아래로 5px의 마진을 추가합니다 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer .footer-logo {\r\n");
      out.write("	font-size: 2em; /* 폰트 크기를 2em으로 설정합니다 */\r\n");
      out.write("	font-weight: bold; /* 폰트를 굵게 설정합니다 */\r\n");
      out.write("	margin-top: 20px; /* 위쪽에 20px의 마진을 추가합니다 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer .footer-links {\r\n");
      out.write("	margin-top: 10px; /* 위쪽에 10px의 마진을 추가합니다 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer .footer-links a {\r\n");
      out.write("	color: #fff; /* 링크 텍스트 색상을 흰색으로 설정합니다 */\r\n");
      out.write("	text-decoration: none; /* 링크의 밑줄을 제거합니다 */\r\n");
      out.write("	margin: 0 10px; /* 좌우에 10px의 마진을 추가하여 링크 간의 간격을 만듭니다 */\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <main>\r\n");
      out.write("        <!-- 페이지의 주요 콘텐츠가 여기에 들어갑니다 -->\r\n");
      out.write("    </main>\r\n");
      out.write("    <footer>\r\n");
      out.write("        <div class=\"footer-line\"></div>\r\n");
      out.write("        <div class=\"footer-text\">회사소개 이용약관 개인정보처리방침 이메일무단수집거부 단체주문 제휴문의 입점신청 멤버쉽 안내</div>\r\n");
      out.write("        <div class=\"footer-logo\">saren</div>\r\n");
      out.write("        <div class=\"footer-links\">\r\n");
      out.write("            <a href=\"#\">고객센터</a>\r\n");
      out.write("            <a href=\"#\">공지사항</a>\r\n");
      out.write("            <a href=\"#\">매장찾기</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"footer-text\">\r\n");
      out.write("            77 ANT 빌딩 1층, 월드컵북로4길 마포구 서울특별시(동교동) 대표 : 이종경 사업자등록번호: 178-59-41720 사업자정보확인 통신판매업신고: 2015-서울동교-02894\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"footer-text\">\r\n");
      out.write("            호스팅서비스: SAREN(주)패션부문 KG이니시스 구매안전서비스 이용확인 서비스가입사실확인\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"footer-text\">\r\n");
      out.write("            대표전화 1599-0007(유료) 080-700-1472(무료)\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"footer-text\">\r\n");
      out.write("            Copyright © SHINHAN BANK. All rights reserved.\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("   <script type=\"text/javascript\">\r\n");
      out.write("	    $(function() {\r\n");
      out.write("	    	\r\n");
      out.write(" 			//대표 주소로 설정 \r\n");
      out.write("	         $('.address-box').click(function() {\r\n");
      out.write("	 			console.log($('#masterTest').text().trim());\r\n");
      out.write("\r\n");
      out.write("	 			var masterCheck = $('#masterTest').text().trim();\r\n");
      out.write("	 			\r\n");
      out.write("	 			// 클릭된 address-box를 찾음\r\n");
      out.write("        		var addr_num = $(this).find('input[type=\"hidden\"]').val();\r\n");
      out.write("        		console.log('변경할 주소 번호: ' + addr_num);\r\n");
      out.write("        		\r\n");
      out.write("        		 //var addressBox = $(this).parent('.address-box');\r\n");
      out.write("            	 //var addr_num = addressBox.find('input[type=\"hidden\"]').val();\r\n");
      out.write("        		\r\n");
      out.write("	       	    \r\n");
      out.write("	 			console.log(\"대표임\");\r\n");
      out.write("	 				\r\n");
      out.write(" 				if(confirm(\"대표 주소로 설정하시겠습니까?\")){\r\n");
      out.write("	 				\r\n");
      out.write("	 	       	    // 삭제 요청을 위한 데이터\r\n");
      out.write("	 	       	    var addrData = {\r\n");
      out.write("	 	       	        addr_num: addr_num\r\n");
      out.write("	 	       	    };\r\n");
      out.write(" 				\r\n");
      out.write("	 				//대표로 update\r\n");
      out.write("	 				 $.ajax({\r\n");
      out.write("	 	                type: \"POST\",\r\n");
      out.write("	 	                url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/customer/masterAddrUpdate.do\",\r\n");
      out.write("		                contentType: 'application/json',\r\n");
      out.write("		                data: JSON.stringify(addrData),\r\n");
      out.write("	 	                success: function(resultData) {\r\n");
      out.write("	 	                   /* if(resultData == 1){\r\n");
      out.write("	 	                    	alert(\"대표 배송지 설정 완료\");\r\n");
      out.write("	 	                    	// 현재 페이지 새로고침\r\n");
      out.write("	 	                       location.reload();\r\n");
      out.write("	 	                    }else{\r\n");
      out.write("	 	                    	alert(\"오류가 발생되었습니다. 다시 시도해 주세요.\");\r\n");
      out.write("	 	                    	location.reload();\r\n");
      out.write("	 	                    }\r\n");
      out.write("	 	                    */\r\n");
      out.write("	 	                	 if(resultData == 1){\r\n");
      out.write("	 	                        alert(\"대표 배송지 설정 완료\");\r\n");
      out.write("\r\n");
      out.write("	 	                        // 대표 주소가 업데이트되었음을 DOM에 반영\r\n");
      out.write("	 	                        $('.label').each(function() {\r\n");
      out.write("	 	                            if ($(this).text().trim() === \"대표\") {\r\n");
      out.write("	 	                                $(this).text(\"\");\r\n");
      out.write("	 	                            }\r\n");
      out.write("	 	                        });\r\n");
      out.write("	 	                        $(this).find('.label').text(\"대표\");\r\n");
      out.write("	 	                       location.reload();\r\n");
      out.write("	 	                       \r\n");
      out.write("	 	                    } else {\r\n");
      out.write("	 	                        alert(\"오류가 발생되었습니다. 다시 시도해 주세요.\");\r\n");
      out.write("	 	                    }\r\n");
      out.write("	 	                    \r\n");
      out.write("	 	                },\r\n");
      out.write("	 	                error: function(request, status, error) {\r\n");
      out.write("	 	                    console.log(\"code:\" + request.status + \"\\n\" + \"message:\" + request.responseText + \"\\n\" + \"error:\" + error);\r\n");
      out.write("	 	                }\r\n");
      out.write("	 				 });\r\n");
      out.write("	 				\r\n");
      out.write("	 			}else{\r\n");
      out.write("	 				\r\n");
      out.write(" 				    return;\r\n");
      out.write("	 			}\r\n");
      out.write("	 				\r\n");
      out.write("	 		}); \r\n");
      out.write("	    	\r\n");
      out.write("	    	//비밀번호 확인하러 가는 버튼 \r\n");
      out.write("		 	$('#loadButton').click(function(e) {\r\n");
      out.write("\r\n");
      out.write("		 		$.ajax({\r\n");
      out.write("	                type: \"GET\",\r\n");
      out.write("	                url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/customer/myInfoUpdate.do\",\r\n");
      out.write("	                success: function(resultData) {\r\n");
      out.write("	                	console.log(\"페이지 이동\");\r\n");
      out.write("	                },\r\n");
      out.write("	                error: function(request, status, error) {\r\n");
      out.write("	                    console.log(\"code:\" + request.status + \"\\n\" + \"message:\" + request.responseText + \"\\n\" + \"error:\" + error);\r\n");
      out.write("	                }\r\n");
      out.write("	            });\r\n");
      out.write("         		\r\n");
      out.write("			});\r\n");
      out.write("	    	\r\n");
      out.write("	    	//배송지 팝업 확인 버튼\r\n");
      out.write("	    	$('#submitBtn').on('click', function(e) {\r\n");
      out.write("	    		e.preventDefault();\r\n");
      out.write("	    		\r\n");
      out.write("	    		var isMasterAddrChecked = $(\"#isMasterAddr\").is(\":checked\") ? \"Y\" : \"N\";\r\n");
      out.write("	    		var addrAddFormData = {\r\n");
      out.write("	                zipcode: $(\"#sample6_postcode\").val(),\r\n");
      out.write("	                main_address: $(\"#sample6_address\").val(),\r\n");
      out.write("	                detail_address: $(\"#sample6_detailAddress\").val(),\r\n");
      out.write("	                is_master_addr:  isMasterAddrChecked,\r\n");
      out.write("	                sub_address: $(\"#sample6_extraAddress\").val()\r\n");
      out.write("	            };\r\n");
      out.write("	    		console.log(addrAddFormData);\r\n");
      out.write("	            $.ajax({\r\n");
      out.write("	                type: \"POST\",\r\n");
      out.write("	                url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/customer/myAddrInsert.do\",\r\n");
      out.write("	                data: JSON.stringify(addrAddFormData),\r\n");
      out.write("	                contentType: 'application/json',\r\n");
      out.write("	                dataType: 'json',\r\n");
      out.write("	                success: function(resultData) {\r\n");
      out.write("	                    if(resultData == 1){\r\n");
      out.write("	                    	alert(\"배송지가 추가되었습니다.\");\r\n");
      out.write("	                    	location.reload();\r\n");
      out.write("	                    	\r\n");
      out.write("	                    }else{\r\n");
      out.write("	                    	alert(\"오류가 발생되었습니다. 다시 시도해 주세요.\");\r\n");
      out.write("	                    	location.reload();\r\n");
      out.write("	                    }\r\n");
      out.write("	                },\r\n");
      out.write("	                error: function(request, status, error) {\r\n");
      out.write("	                    console.log(\"code:\" + request.status + \"\\n\" + \"message:\" + request.responseText + \"\\n\" + \"error:\" + error);\r\n");
      out.write("	                }\r\n");
      out.write("	            });\r\n");
      out.write("	    	});\r\n");
      out.write("	    	\r\n");
      out.write("	    });\r\n");
      out.write("    </script>\r\n");
      out.write("	<script>\r\n");
      out.write("	    function sample6_execDaumPostcode() {\r\n");
      out.write("	        new daum.Postcode({\r\n");
      out.write("	            oncomplete: function(data) {\r\n");
      out.write("	                // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("	\r\n");
      out.write("	                // 각 주소의 노출 규칙에 따라 주소를 조합한다.\r\n");
      out.write("	                // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("	                var addr = ''; // 주소 변수\r\n");
      out.write("	                var extraAddr = ''; // 참고항목 변수\r\n");
      out.write("	\r\n");
      out.write("	                //사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.\r\n");
      out.write("	                if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우\r\n");
      out.write("	                    addr = data.roadAddress;\r\n");
      out.write("	                } else { // 사용자가 지번 주소를 선택했을 경우(J)\r\n");
      out.write("	                    addr = data.jibunAddress;\r\n");
      out.write("	                }\r\n");
      out.write("	\r\n");
      out.write("	                // 사용자가 선택한 주소가 도로명 타입일때 참고항목을 조합한다.\r\n");
      out.write("	                if(data.userSelectedType === 'R'){\r\n");
      out.write("	                    // 법정동명이 있을 경우 추가한다. (법정리는 제외)\r\n");
      out.write("	                    // 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\r\n");
      out.write("	                    if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){\r\n");
      out.write("	                        extraAddr += data.bname;\r\n");
      out.write("	                    }\r\n");
      out.write("	                    // 건물명이 있고, 공동주택일 경우 추가한다.\r\n");
      out.write("	                    if(data.buildingName !== '' && data.apartment === 'Y'){\r\n");
      out.write("	                        extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);\r\n");
      out.write("	                    }\r\n");
      out.write("	                    // 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.\r\n");
      out.write("	                    if(extraAddr !== ''){\r\n");
      out.write("	                        extraAddr = ' (' + extraAddr + ')';\r\n");
      out.write("	                    }\r\n");
      out.write("	                    // 조합된 참고항목을 해당 필드에 넣는다.\r\n");
      out.write("	                    document.getElementById(\"sample6_extraAddress\").value = extraAddr;\r\n");
      out.write("	                \r\n");
      out.write("	                } else {\r\n");
      out.write("	                    document.getElementById(\"sample6_extraAddress\").value = '';\r\n");
      out.write("	                }\r\n");
      out.write("	\r\n");
      out.write("	                // 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("	                document.getElementById('sample6_postcode').value = data.zonecode;\r\n");
      out.write("	                document.getElementById(\"sample6_address\").value = addr;\r\n");
      out.write("	                // 커서를 상세주소 필드로 이동한다.\r\n");
      out.write("	                document.getElementById(\"sample6_detailAddress\").focus();\r\n");
      out.write("	            }\r\n");
      out.write("	        }).open();\r\n");
      out.write("	    }\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/customer/myInfoUpdate.jsp(3,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path");
      // /WEB-INF/views/customer/myInfoUpdate.jsp(3,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/customer/myInfoUpdate.jsp(3,0) '${pageContext.servletContext.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.servletContext.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /WEB-INF/views/customer/../common/header.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("path");
      // /WEB-INF/views/customer/../common/header.jsp(4,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/customer/../common/header.jsp(4,0) '${pageContext.servletContext.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.servletContext.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f2_reused = false;
    try {
      _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f2.setParent(null);
      // /WEB-INF/views/customer/../common/header.jsp(7,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setVar("isLoggedIn");
      // /WEB-INF/views/customer/../common/header.jsp(7,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/customer/../common/header.jsp(7,0) '${not empty sessionScope.member}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${not empty sessionScope.member}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
      if (_jspx_th_c_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
      _jspx_th_c_005fset_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("					");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("					");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/customer/../common/header.jsp(30,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${isLoggedIn}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("						<li>\r\n");
          out.write("							<a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member_test/logout.do\"> \r\n");
          out.write("								<p>로그아웃</p>\r\n");
          out.write("								<img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/images/icon-logout.png\" alt=\"로그아웃\">\r\n");
          out.write("							</a>\r\n");
          out.write("						</li>\r\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("						<li>\r\n");
          out.write("							<a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member_test/login.do\" id=\"loginLink\"> \r\n");
          out.write("								<p>로그인</p>\r\n");
          out.write("								<img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/images/icon-login.gif\" alt=\"로그인\">\r\n");
          out.write("							</a>\r\n");
          out.write("						</li>\r\n");
          out.write("						<li>\r\n");
          out.write("							<a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member_test/signup\">\r\n");
          out.write("								<p>회원가입</p>\r\n");
          out.write("								<img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/images/icon-sign-in.png\" alt=\"회원가입\">\r\n");
          out.write("							</a>\r\n");
          out.write("						</li>\r\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/customer/myInfoUpdate.jsp(276,6) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/customer/myInfoUpdate.jsp(276,6) '${addrlist}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${addrlist}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/customer/myInfoUpdate.jsp(276,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("addr");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("							<div class=\"address-box-wrap\">\r\n");
            out.write("								<div class=\"address-box\">\r\n");
            out.write("									<div class=\"label\" id=\"masterTest\">\r\n");
            out.write("										");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${addr.IS_MASTER_ADDR == \"Y\" ? \"대표\" : \"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\r\n");
            out.write("									</div>\r\n");
            out.write("									<input type=\"hidden\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${addr.ADDR_NUM}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("									<div class=\"info\">\r\n");
            out.write("										");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${addr.MEMBER_NAME}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("<strong>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${addr.PHONE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</strong><br> >\r\n");
            out.write("										(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${addr.ZIPCODE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(") \r\n");
            out.write("										");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${addr.MAIN_ADDRESS}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\r\n");
            out.write("										");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${addr.DETAIL_ADDRESS}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\r\n");
            out.write("										");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${addr.SUB_ADDRESS}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\r\n");
            out.write("									</div>\r\n");
            out.write("								</div>\r\n");
            out.write("								<button class=\"delete-btn\">삭제</button>\r\n");
            out.write("							</div>\r\n");
            out.write("						");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f3 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f3_reused = false;
    try {
      _jspx_th_c_005fset_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f3.setParent(null);
      // /WEB-INF/views/customer/../common/footer.jsp(3,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f3.setVar("path");
      // /WEB-INF/views/customer/../common/footer.jsp(3,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f3.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/customer/../common/footer.jsp(3,0) '${pageContext.servletContext.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.servletContext.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f3 = _jspx_th_c_005fset_005f3.doStartTag();
      if (_jspx_th_c_005fset_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f3);
      _jspx_th_c_005fset_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f3_reused);
    }
    return false;
  }
}
