/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-07-15 17:02:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class common_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/sh3/workspace-sts-3.9.18/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Shinhan_SW_1st_TeamProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1719295440415L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("@charset \"UTF-8\";\r\n");
      out.write("body {\r\n");
      out.write("    font-family: Arial, sans-serif;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    background-color: #f8f9fa; /* 통일된 배경색 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar {\r\n");
      out.write("    height: 100vh;\r\n");
      out.write("    position: fixed;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    width: 250px;\r\n");
      out.write("    background-color: #343a40;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    padding-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar a {\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    display: block;\r\n");
      out.write("    padding: 10px 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar img {\r\n");
      out.write("    padding: 10px 20px;\r\n");
      out.write("    width: 100%; /* 원하는 너비 */\r\n");
      out.write("    height: auto; /* 높이는 비율에 맞게 자동 조절 */\r\n");
      out.write("    max-width: 100%; /* 최대 너비 설정 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar a:hover {\r\n");
      out.write("    background-color: #495057;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar .dropdown-btn {\r\n");
      out.write("    color: white;\r\n");
      out.write("    padding: 10px 20px;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    display: block;\r\n");
      out.write("    background: none;\r\n");
      out.write("    border: none;\r\n");
      out.write("    outline: none;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    text-align: left;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar .dropdown-container {\r\n");
      out.write("    display: none;\r\n");
      out.write("    background-color: #262626;\r\n");
      out.write("    padding-left: 8px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar .dropdown-btn:hover + .dropdown-container,\r\n");
      out.write(".sidebar .dropdown-container:hover {\r\n");
      out.write("    display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header {\r\n");
      out.write("    width: calc(100% - 250px);\r\n");
      out.write("    margin-left: 250px;\r\n");
      out.write("    background-color: #f8f9fa;\r\n");
      out.write("    color: black;\r\n");
      out.write("    padding: 10px 20px;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: space-between;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header .search-container {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header .search-box {\r\n");
      out.write("    max-width: 300px;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 38px; /* 검색창 높이를 줄임 */\r\n");
      out.write("    margin-right: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header .account {\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header .account-name {\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    padding: 10px 20px;\r\n");
      out.write("    background-color: #f8f9fa;\r\n");
      out.write("    border: none;\r\n");
      out.write("    color: black;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header .dropdown-account {\r\n");
      out.write("    display: none;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    right: 0;\r\n");
      out.write("    background-color: #f8f9fa;\r\n");
      out.write("    min-width: 160px;\r\n");
      out.write("    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);\r\n");
      out.write("    z-index: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header .dropdown-account a {\r\n");
      out.write("    color: black;\r\n");
      out.write("    padding: 12px 16px;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header .dropdown-account a:hover {\r\n");
      out.write("    background-color: #ddd;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header .account:hover .dropdown-account {\r\n");
      out.write("    display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".content {\r\n");
      out.write("    margin-top: 60px;\r\n");
      out.write("    margin-left: 250px;\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("    width: calc(100% - 250px);\r\n");
      out.write("    background-color: #f8f9fa;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card {\r\n");
      out.write("    margin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".chart-container {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    height: 400px; /* 높이를 크게 설정 */\r\n");
      out.write("    width: 100%; /* 너비를 꽉 차게 설정 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table-container {\r\n");
      out.write("    margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn {\r\n");
      out.write("    background-color: #007bff;\r\n");
      out.write("    color: white;\r\n");
      out.write("    height: 38px; /* 검색 버튼 높이를 검색창과 맞춤 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card .card-title {\r\n");
      out.write("    font-size: 1.25rem;\r\n");
      out.write("    margin-bottom: 1rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card .card-subtitle {\r\n");
      out.write("    font-size: 1rem;\r\n");
      out.write("    color: #6c757d;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card .card-text {\r\n");
      out.write("    font-size: 0.875rem;\r\n");
      out.write("    color: #6c757d;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".no-data-message {\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    color: #6c757d;\r\n");
      out.write("    margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-container {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    width: 50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-container form {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".input-group {\r\n");
      out.write("    width: 80%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-control {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    width: auto;\r\n");
      out.write("    vertical-align: middle;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-control-search-box {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    width: auto;\r\n");
      out.write("    flex-grow: 1;\r\n");
      out.write("    vertical-align: middle;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".input-group .form-control {\r\n");
      out.write("    width: auto;\r\n");
      out.write("    flex: 0 1 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-results-list {\r\n");
      out.write("    list-style-type: none; /* 목록 항목 앞에 기호를 없앰 */\r\n");
      out.write("    margin-top: 10px;\r\n");
      out.write("    padding-left: 0; /* 내부 패딩 제거 */\r\n");
      out.write("    max-height: 250px; /* 최대 높이 설정 */\r\n");
      out.write("    overflow-y: auto; /* 내용이 넘칠 경우 스크롤바 표시 */\r\n");
      out.write("    width: 100%; /* 전체 너비 */\r\n");
      out.write("    background-color: #fff;\r\n");
      out.write("    border: 1px solid #ccc;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    z-index: 1000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-results-list li {\r\n");
      out.write("    padding: 8px;\r\n");
      out.write("    border-bottom: 1px solid #ccc; /* 각 항목을 구분짓는 선 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-results-list li:hover {\r\n");
      out.write("    background-color: #f8f8f8; /* 마우스 오버 시 배경 색상 변경 */\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("function f_search() {\r\n");
      out.write("    $.ajax({\r\n");
      out.write("        url: \"search_results\",\r\n");
      out.write("        data: {\r\n");
      out.write("            searchType: $(\"#searchType\").val(),\r\n");
      out.write("            keyword: $(\"#keyword\").val()\r\n");
      out.write("        },\r\n");
      out.write("        success: function(responsedata) {\r\n");
      out.write("            var resultsHtml = '';\r\n");
      out.write("            if (responsedata.length === 0) {\r\n");
      out.write("                resultsHtml = '<li>No results found.</li>';\r\n");
      out.write("            } else {\r\n");
      out.write("                responsedata.forEach(function(item) {\r\n");
      out.write("                    resultsHtml += '<li>' + item.member_name + ' (' + item.member_brand + ')</li>';\r\n");
      out.write("                });\r\n");
      out.write("            }\r\n");
      out.write("            $('#searchResults').html(resultsHtml);\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div class=\"sidebar\">\r\n");
      out.write("    <h2 class=\"text-center\">\r\n");
      out.write("        <a href=\"admin_page\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/logo_main.png\" alt=\"메인로고\" class=\"logo\"></a>\r\n");
      out.write("    </h2>    \r\n");
      out.write("    \r\n");
      out.write("    <a href=\"admin_page\">Dashboard</a>\r\n");
      out.write("    \r\n");
      out.write("    <button class=\"dropdown-btn\">판매자</button>\r\n");
      out.write("    <div class=\"dropdown-container\">\r\n");
      out.write("        <a href=\"admin_seller_list\">판매자 목록</a> \r\n");
      out.write("        <a href=\"admin_seller_register\">판매자 등록</a> \r\n");
      out.write("        <a href=\"admin_seller_prod\">판매자 판매 상품</a>\r\n");
      out.write("        <a href=\"admin_seller_rent\">판매자 대여 상품</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <button class=\"dropdown-btn\">고객</button>\r\n");
      out.write("    <div class=\"dropdown-container\">\r\n");
      out.write("        <a href=\"admin_customer_list\">고객 목록</a> \r\n");
      out.write("        <a href=\"admin_customer_orderlist\">고객 주문 목록</a> \r\n");
      out.write("        <a href=\"admin_customer_rentlist\">고객 대여 목록</a> \r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <button class=\"dropdown-btn\">공지 / 이벤트 / 문의사항</button>\r\n");
      out.write("    <div class=\"dropdown-container\">\r\n");
      out.write("        <a href=\"admin_notice_list\">공지사항 목록</a>         \r\n");
      out.write("       	<a href=\"admin_event_list\">이벤트 목록</a> \r\n");
      out.write("       	<a href=\"admin_faq_list\">문의 목록</a>        \r\n");
      out.write("    </div>    \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("    <div id=\"searchResults\" class=\"search-results\"></div>\r\n");
      out.write("    <div class=\"account\">\r\n");
      out.write("        <button class=\"account-name\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${aDto.admin_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</button>\r\n");
      out.write("        <div class=\"dropdown-account\">\r\n");
      out.write("            <a href=\"admin_mypage\">내 정보</a> \r\n");
      out.write("            <a href=\"admin_logout\">로그아웃</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/admin/common.jsp(3,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path");
      // /WEB-INF/views/admin/common.jsp(3,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/admin/common.jsp(3,0) '${pageContext.servletContext.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.servletContext.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
